// react/src/feature-module/agent/agentGridSidebar/index.tsx
import React from 'react'
import { Link } from 'react-router-dom'
import ImageWithBasePath from '../../../core/img'
import AgentSidebar from '../agentSidebar'
import BreadCrumb from '../../../core/common/breadCrumb'
import { all_routes } from '../../router/all_routes'


const AgentGridSidebar = () => {
    const routes = all_routes
    return (
        <div>
            {/* Breadcrumb */}
            <BreadCrumb title="Agent Grid With Sidebar" pageTitle="Home" />
            {/* Breadcrumb */}
            {/* Content */}
            <div className="content">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-3 theiaStickySidebar">
                            {/* Sidebar */}
                           <AgentSidebar/>
                            {/* /Sidebar */}
                        </div>
                        <div className="col-lg-9">
                            <div className="row">
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agentDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt='img'
                                                    src="assets/img/agents/agent-01.jpg"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>30 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>5.0</span>(20 Reviews)
                                                </p>
                                            </div>
                                            <h6>
                                                <Link to={routes.agentDetails}>Mike Rutter</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-user-voice" />
                                                Selling Agent
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agentDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt='img'
                                                    src="assets/img/agents/agent-02.jpg"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>40 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>5.0</span>(8 Reviews)
                                                </p>
                                            </div>
                                            <h6>
                                                <Link to={routes.agentDetails}>Pamela</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-user-voice" />
                                                Buying Agent
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agentDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt='img'
                                                    src="assets/img/agents/agent-03.jpg"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>50 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>5.0</span>(5 Reviews)
                                                </p>
                                            </div>
                                            <h6>
                                                <Link to={routes.agentDetails}>Enriquez</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-user-voice" />
                                                Selling Agent
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agentDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt='img'
                                                    src="assets/img/agents/agent-04.jpg"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>45 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>5.0</span>(11 Reviews)
                                                </p>
                                            </div>
                                            <h6>
                                                <Link to={routes.agentDetails}>Lowe</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-user-voice" />
                                                Selling Agent
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agentDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt='img'
                                                    src="assets/img/agents/agent-05.jpg"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>32 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>5.0</span>(12 Reviews)
                                                </p>
                                            </div>
                                            <h6>
                                                <Link to={routes.agentDetails}>Gregory</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-user-voice" />
                                                Buying Agent
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agentDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt='img'
                                                    src="assets/img/agents/agent-06.jpg"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>60 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>5.0</span>(10 Reviews)
                                                </p>
                                            </div>
                                            <h6>
                                                <Link to={routes.agentDetails}>Lee</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-user-voice" />
                                                Selling Agent
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Pagination */}
                                <div className="col-lg-12">
                                    <div className="grid-pagination">
                                        <ul className="pagination justify-content-center">
                                            <li className="page-item prev">
                                                <Link className="page-link" to="#">
                                                    <i className="fa-solid fa-arrow-left" /> Prev
                                                </Link>
                                            </li>
                                            <li className="page-item">
                                                <Link className="page-link" to="#">
                                                    1
                                                </Link>
                                            </li>
                                            <li className="page-item active">
                                                <Link className="page-link" to="#">
                                                    2
                                                </Link>
                                            </li>
                                            <li className="page-item">
                                                <Link className="page-link" to="#">
                                                    3
                                                </Link>
                                            </li>
                                            <li className="page-item">
                                                <Link className="page-link" to="#">
                                                    4
                                                </Link>
                                            </li>
                                            <li className="page-item next">
                                                <Link className="page-link" to="#">
                                                    Next <i className="fa-solid fa-arrow-right" />
                                                </Link>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                {/* /Pagination */}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Content */}
        </div>
    )
}

export default AgentGridSidebar

// angular/src/app/feature-module/agent/agent-grid-sidebar/agent-grid-sidebar.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../shared/routes/routes';

@Component({
  selector: 'app-agent-grid-sidebar',
  templateUrl: './agent-grid-sidebar.component.html',
  styleUrl: './agent-grid-sidebar.component.scss'
})
export class AgentGridSidebarComponent {
  public routes = routes;
}

<!-- Breadcrumb -->
<div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Agent Grid With Sidebar</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink] = "routes.home">Home </a></li>
                    <li>Agent Grid With Sidebar</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" class="img-fluid" alt="Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->

<!-- Content -->
<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 theiaStickySidebar">

                <!-- Sidebar -->
                <div class="left-sidebar-widget stickybar">
                    <div class="collapse-card">
                        <h4 class="card-title">
                            <a class="collapsed" data-bs-toggle="collapse" href="#search"
                                aria-expanded="false">Search</a>
                        </h4>
                        <div id="search" class="card-collapse collapse show">
                            <ul class="show-list">
                                <li class="review-form">
                                    <label for="Agent Name">Agent Name</label>
                                    <input type="text" class="form-control" placeholder="Enter Name">
                                </li>
                                <li class="review-form">
                                      <label for="Agent Type">Agent Type</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="Selling Agent">Selling Agent</mat-option>
                                        <mat-option value="Buying Agent">Buying Agent</mat-option>
                                    </mat-select>
                                </li>
                                <li class="review-form">
                                      <label for="Select City">Select City</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="Texas">Texas</mat-option>
                                        <mat-option value="New York">New York</mat-option>
                                    </mat-select>
                                </li>
                                <li class="review-form">
                                    <label for="selectarea">Select Area</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="Select">Select</mat-option>
                                        <mat-option value="Oakley">Oakley</mat-option>
                                        <mat-option value="Park Ave">Park Ave</mat-option>
                                    </mat-select>
                                </li>
                                <li class="review-form">
                                    <label for="Select Category">Select Category</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="Villa">Villa</mat-option>
                                        <mat-option value="Apartment">Apartment</mat-option>
                                    </mat-select>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="collapse-card">
                        <h4 class="card-title">
                            <a class="collapsed" data-bs-toggle="collapse" href="#categiries"
                                aria-expanded="false">Categories</a>
                        </h4>
                        <div id="categiries" class="card-collapse collapse show">
                            <ul class="checkbox-list">
                                <li>
                                    <label class="custom_check">
                                        <input type="checkbox" name="username">
                                        <span class="checkmark"></span> Rental (41)
                                    </label>
                                </li>
                                <li>
                                    <label class="custom_check">
                                        <input type="checkbox" name="username">
                                        <span class="checkmark"></span> Sales (15)
                                    </label>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /Sidebar -->

            </div>

            <div class="col-lg-9">
                <div class="row">
                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">
                        <div class="agent-card card flex-fill">
                            <div class="agent-img">
                                <a [routerLink] = "routes.agentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-01.jpg">
                                </a>
                                <div class="list-feature">
                                    <span>30 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <p class="rating-review"><span>5.0</span>(20 Reviews)</p>
                                </div>
                                <h6>
                                    <a [routerLink] = "routes.agentDetails">Mike Rutter</a>
                                </h6>
                                <p><i class="bx bx-user-voice"></i>Selling Agent</p>
                            </div>
                        </div>
                    </div>
                    <!-- /Agent -->

                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">
                        <div class="agent-card card flex-fill">
                            <div class="agent-img">
                                <a [routerLink] = "routes.agentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-02.jpg">
                                </a>
                                <div class="list-feature">
                                    <span>40 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <p class="rating-review"><span>5.0</span>(8 Reviews)</p>
                                </div>
                                <h6>
                                    <a [routerLink] = "routes.agentDetails">Pamela</a>
                                </h6>
                                <p><i class="bx bx-user-voice"></i>Buying Agent</p>
                            </div>
                        </div>
                    </div>
                    <!-- /Agent -->

                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">
                        <div class="agent-card card flex-fill">
                            <div class="agent-img">
                                <a [routerLink] = "routes.agentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-03.jpg">
                                </a>
                                <div class="list-feature">
                                    <span>50 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <p class="rating-review"><span>5.0</span>(5 Reviews)</p>
                                </div>
                                <h6>
                                    <a [routerLink] = "routes.agentDetails">Enriquez</a>
                                </h6>
                                <p><i class="bx bx-user-voice"></i>Selling Agent</p>
                            </div>
                        </div>
                    </div>
                    <!-- /Agent -->

                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">
                        <div class="agent-card card flex-fill">
                            <div class="agent-img">
                                <a [routerLink] = "routes.agentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-04.jpg">
                                </a>
                                <div class="list-feature">
                                    <span>45 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <p class="rating-review"><span>5.0</span>(11 Reviews)</p>
                                </div>
                                <h6>
                                    <a [routerLink] = "routes.agentDetails">Lowe</a>
                                </h6>
                                <p><i class="bx bx-user-voice"></i>Selling Agent</p>
                            </div>
                        </div>
                    </div>
                    <!-- /Agent -->

                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">
                        <div class="agent-card card flex-fill">
                            <div class="agent-img">
                                <a [routerLink] = "routes.agentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-05.jpg">
                                </a>
                                <div class="list-feature">
                                    <span>32 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <p class="rating-review"><span>5.0</span>(12 Reviews)</p>
                                </div>
                                <h6>
                                    <a [routerLink] = "routes.agentDetails">Gregory</a>
                                </h6>
                                <p><i class="bx bx-user-voice"></i>Buying Agent</p>
                            </div>
                        </div>
                    </div>
                    <!-- /Agent -->

                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">
                        <div class="agent-card card flex-fill">
                            <div class="agent-img">
                                <a [routerLink] = "routes.agentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-06.jpg">
                                </a>
                                <div class="list-feature">
                                    <span>60 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <p class="rating-review"><span>5.0</span>(10 Reviews)</p>
                                </div>
                                <h6>
                                    <a [routerLink] = "routes.agentDetails">Lee</a>
                                </h6>
                                <p><i class="bx bx-user-voice"></i>Selling Agent</p>
                            </div>
                        </div>
                    </div>
                    <!-- /Agent -->

                    <!-- Pagination -->
                    <div class="col-lg-12">
                        <div class="grid-pagination">
                            <ul class="pagination justify-content-center">
                                <li class="page-item prev">
                                    <a class="page-link" href="javascript:void(0);"><i class="fa-solid fa-arrow-left"></i> Prev</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="javascript:void(0);">1</a>
                                </li>
                                <li class="page-item active">
                                    <a class="page-link" href="javascript:void(0);">2</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="javascript:void(0);">3</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="javascript:void(0);">4</a>
                                </li>
                                <li class="page-item next">
                                    <a class="page-link" href="javascript:void(0);">Next <i class="fa-solid fa-arrow-right"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /Pagination -->

                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Content -->
