// angular/src/app/feature-module/pages/error/error-500/error-500.component.ts
import { Component, OnDestroy, Renderer2 } from '@angular/core';
import { CommonService } from '../../../../shared/common/common.service';
import { routes } from '../../../../shared/routes/routes';

@Component({
  selector: 'app-error-500',
  templateUrl: './error-500.component.html',
  styleUrl: './error-500.component.scss'
})
export class Error500Component implements OnDestroy {
  base = '';
  page = '';
  last = '';
  public routes = routes;
  constructor(
    private common: CommonService,
    private renderer: Renderer2
  ) {
    this.common.base.subscribe((res: string) => {
      this.base = res;
    });
    this.common.page.subscribe((res: string) => {
      this.page = res;
    });
    this.common.last.subscribe((res: string) => {
      this.last = res;
    });
    if(this.page == 'error-500') {
      this.renderer.addClass(document.body, 'error-page');
      this.renderer.addClass(document.body, 'login-body');
      this.renderer.addClass(document.body, 'p-0');
    }
  }
  ngOnDestroy(): void {
    this.renderer.removeClass(document.body, 'error-page');
    this.renderer.removeClass(document.body, 'login-body');
    this.renderer.removeClass(document.body, 'p-0');
  }
}

<div class="container">
    <!-- Header -->
    <header class="log-header">
        <a [routerLink] = "routes.home"><img class="img-fluid logo-dark" src="assets/img/logo.svg" alt="Logo"></a>
    </header>
    <!-- /Header -->
    <div class="error-box">
        <img src="assets/img/500.png" class="img-fluid" alt="Unexpected error">
        <h1>500 Unexpected Error</h1>
        <p class="error-content">We’re having some issuesat the moment. we’ll have it fixed in no time.</p>
        <div class="back-button">					
            <a [routerLink] = "routes.home" class="btn">Back to Home</a>
        </div>
    </div>
</div>

// react/src/feature-module/pages/error/error500.tsx
import React from "react";
import ImageWithBasePath from "../../../core/img";
import { Link } from "react-router-dom";
import { all_routes } from "../../router/all_routes";

const Error500 = () => {
  const routes = all_routes
  return (
    <div className="login-body">
      <div className="container">
        {/* Header */}
        <header className="log-header">
          <Link to={routes.home}>
            <ImageWithBasePath
              className="img-fluid logo-dark"
              src="assets/img/logo.svg"
              alt="Logo"
            />
          </Link>
        </header>
        {/* /Header */}
        <div className="error-box">
          <ImageWithBasePath
            src="assets/img/500.png"
            className="img-fluid"
            alt="Unexpected error"
          />
          <h1>500 Unexpected Error</h1>
          <p className="error-content">
            We’re having some issuesat the moment. we’ll have it fixed in no
            time.
          </p>
          <div className="back-button">
            <Link to={routes.home} className="btn">
              Back to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Error500;
