// angular/src/app/feature-module/blog/blog-list/blog-list.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../shared/routes/routes';

@Component({
  selector: 'app-blog-list',
  templateUrl: './blog-list.component.html',
  styleUrl: './blog-list.component.scss'
})
export class BlogListComponent {
  public routes = routes;
}

<!-- Breadcrumb -->
<div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Blog List</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink] = "routes.home">Home </a></li>
                    <li>Blog List</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" alt="Line Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->

<!-- Blog List-->
<div class="section blog-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-lg-12 col-md-12 d-lg-flex">
                        <div class="blog grid-blog">
                            <div class="blog-image-list">
                                <a [routerLink] = "routes.blogDetails"><img class="img-fluid"
                                        src="assets/img/blog/blog-list-01.jpg" alt="Post Image"></a>
                            </div>
                            <div class="blog-content">
                                <div class="blog-list-date">
                                    <ul class="meta-item-list">
                                        <li class="blog-category mb-0">
                                            <a href="javascript:void(0)"><span>Property</span></a>
                                        </li>
                                        <li class="date-icon">
                                            <div class="post-author">
                                                <div class="post-author-img">
                                                    <img src="assets/img/profiles/avatar-01.jpg" alt="author">
                                                </div>
                                                <a href="javascript:void(0)"> <span> Alphonsa Daniel </span></a>
                                            </div>
                                            <i class="fa-solid fa-calendar-days"></i> <span>Feb 6, 2023</span>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="blog-title"><a [routerLink] = "routes.blogDetails">The most popular cities for
                                        homebuyers</a></h3>
                                <p class="blog-description border-0 mb-0 pb-0">There are many variations of passages of
                                    lorem ipsum available, but the majority have...</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 d-lg-flex">
                        <div class="blog grid-blog">
                            <div class="blog-image-list">
                                <a [routerLink] = "routes.blogDetails"><img class="img-fluid"
                                        src="assets/img/blog/blog-list-02.jpg" alt="Post Image"></a>
                            </div>
                            <div class="blog-content">
                                <div class="blog-list-date">
                                    <ul class="meta-item-list">
                                        <li class="blog-category mb-0">
                                            <a href="javascript:void(0)"><span>Villa</span></a>
                                        </li>
                                        <li class="date-icon">
                                            <div class="post-author">
                                                <div class="post-author-img">
                                                    <img src="assets/img/profiles/avatar-02.jpg" alt="author">
                                                </div>
                                                <a href="javascript:void(0)"> <span>Francis </span></a>
                                            </div>
                                            <i class="fa-solid fa-calendar-days"></i> <span>Feb 8, 2023</span>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="blog-title"><a [routerLink] = "routes.blogDetails">How to achieve financial
                                        independence</a></h3>
                                <p class="blog-description border-0 mb-0 pb-0">Omnis velit quia. Perspiciatis et
                                    cupiditate. Voluptatum beatae asperiores dolor magnam fuga. Sed fuga est harum quo
                                    nesciunt sint. Optio veniam...Omnis velit quia. Perspiciatis et cupiditate.
                                    Voluptatum beatae..</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 d-lg-flex">
                        <div class="blog grid-blog">
                            <div class="blog-image-list">
                                <a [routerLink] = "routes.blogDetails"><img class="img-fluid"
                                        src="assets/img/blog/blog-list-03.jpg" alt="Post Image"></a>
                            </div>
                            <div class="blog-content">
                                <div class="blog-list-date">
                                    <ul class="meta-item-list">
                                        <li class="blog-category mb-0">
                                            <a href="javascript:void(0)"><span>House</span></a>
                                        </li>
                                        <li class="date-icon">
                                            <div class="post-author">
                                                <div class="post-author-img">
                                                    <img src="assets/img/profiles/avatar-03.jpg" alt="author">
                                                </div>
                                                <a href="javascript:void(0)"> <span> Eric Krok </span></a>
                                            </div>
                                            <i class="fa-solid fa-calendar-days"></i> <span>Feb 9, 2023</span>
                                        </li>
                                    </ul>
                                </div>
                                <h3 class="blog-title"><a [routerLink] = "routes.blogDetails">Learn how real estate really shapes
                                        our future</a></h3>
                                <p class="blog-description border-0 mb-0 pb-0">There are many variations of passages of
                                    lorem ipsum available, but the majority have...</p>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Pagination -->
                <div class="grid-pagination">
                    <ul class="pagination justify-content-center">
                        <li class="page-item prev">
                            <a class="page-link" href="javascript:void(0);"><i class="fa-solid fa-arrow-left"></i> Prev</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="javascript:void(0);">1</a>
                        </li>
                        <li class="page-item active">
                            <a class="page-link" href="javascript:void(0);">2</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="javascript:void(0);">3</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="javascript:void(0);">4</a>
                        </li>
                        <li class="page-item next">
                            <a class="page-link" href="javascript:void(0);">Next <i class="fa-solid fa-arrow-right"></i></a>
                        </li>
                    </ul>
                </div>
                <!-- /Pagination -->

            </div>
            <div class="col-lg-4 theiaStickySidebar">
                <div class="rightsidebar stickybar">
                    <div class="card">
                        <h4>Filter</h4>
                        <div class="filter-content looking-input form-group mb-0">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                    </div>
                    <div class="card">
                        <h4>Categories</h4>
                        <ul class="blogcategories-list">
                            <li><a href="javascript:void(0)">Property</a></li>
                            <li><a href="javascript:void(0)">Villa</a></li>
                            <li><a href="javascript:void(0)">House</a></li>
                            <li><a href="javascript:void(0)">Guest House</a></li>
                            <li><a href="javascript:void(0)">Factory</a></li>
                            <li><a href="javascript:void(0)">Godown</a></li>
                        </ul>
                    </div>
                    <div class="card">
                        <h4>Top Article</h4>
                        <div class="article">
                            <div class="article-blog">
                                <a [routerLink] = "routes.blogDetails">
                                    <img class="img-fluid" src="assets/img/blog/blog-7.jpg" alt="Blog">
                                </a>
                            </div>
                            <div class="article-content">
                                <h5><a [routerLink] = "routes.blogDetails">Great Business Tips in 2023</a></h5>
                                <div class="article-date">
                                    <i class="fa-solid fa-calendar-days"></i>
                                    <span>Jan 6, 2023</span>
                                </div>
                            </div>
                        </div>
                        <div class="article">
                            <div class="article-blog">
                                <a [routerLink] = "routes.blogDetails">
                                    <img class="img-fluid" src="assets/img/blog/blog-8.jpg" alt="Blog">
                                </a>
                            </div>
                            <div class="article-content">
                                <h5><a [routerLink] = "routes.blogDetails">Excited News About Buildings.</a></h5>
                                <div class="article-date">
                                    <i class="fa-solid fa-calendar-days"></i>
                                    <span>Feb 5, 2023</span>
                                </div>
                            </div>
                        </div>
                        <div class="article">
                            <div class="article-blog">
                                <a [routerLink] = "routes.blogDetails">
                                    <img class="img-fluid" src="assets/img/blog/blog-9.jpg" alt="Blog">
                                </a>
                            </div>
                            <div class="article-content">
                                <h5><a [routerLink] = "routes.blogDetails">8 Amazing Tricks About Build Dream..</a></h5>
                                <div class="article-date">
                                    <i class="fa-solid fa-calendar-days"></i>
                                    <span>October 6, 2022</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Blog Grid-->

// react/src/feature-module/blog/blogList/index.tsx
import React from 'react'
import ImageWithBasePath from '../../../core/img'
import { Link } from 'react-router-dom'
import BreadCrumb from '../../../core/common/breadCrumb'
import { all_routes } from '../../router/all_routes'


const BlogList = () => {
    const routes = all_routes
    return (
        <div>
            {/* Breadcrumb */}
            <BreadCrumb title="Blog List" pageTitle="Home" />
            {/* Breadcrumb */}
            {/* Blog List*/}
            <div className="section blog-section">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-8">
                            <div className="row">
                                <div className="col-lg-12 col-md-12 d-lg-flex">
                                    <div className="blog grid-blog">
                                        <div className="blog-image-list">
                                            <Link to={routes.blogDetails}>
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    src="assets/img/blog/blog-list-01.jpg"
                                                    alt='img'
                                                />
                                            </Link>
                                        </div>
                                        <div className="blog-content">
                                            <div className="blog-list-date">
                                                <ul className="meta-item-list">
                                                    <li className="blog-category mb-0">
                                                        <Link to="#">
                                                            <span>Property</span>
                                                        </Link>
                                                    </li>
                                                    <li className="date-icon">
                                                        <div className="post-author">
                                                            <div className="post-author-img">
                                                                <ImageWithBasePath
                                                                    src="assets/img/profiles/avatar-01.jpg"
                                                                    alt="author"
                                                                />
                                                            </div>
                                                            <Link to="#">
                                                                {" "}
                                                                <span> Alphonsa Daniel </span>
                                                            </Link>
                                                        </div>
                                                        <i className="fa-solid fa-calendar-days" />{" "}
                                                        <span>Feb 6, 2023</span>
                                                    </li>
                                                </ul>
                                            </div>
                                            <h3 className="blog-title">
                                                <Link to={routes.blogDetails}>
                                                    The most popular cities for homebuyers
                                                </Link>
                                            </h3>
                                            <p className="blog-description border-0 mb-0 pb-0">
                                                There are many variations of passages of lorem ipsum
                                                available, but the majority have...
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div className="col-lg-12 col-md-12 d-lg-flex">
                                    <div className="blog grid-blog">
                                        <div className="blog-image-list">
                                            <Link to={routes.blogDetails}>
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    src="assets/img/blog/blog-list-02.jpg"
                                                    alt='img'
                                                />
                                            </Link>
                                        </div>
                                        <div className="blog-content">
                                            <div className="blog-list-date">
                                                <ul className="meta-item-list">
                                                    <li className="blog-category mb-0">
                                                        <Link to="#">
                                                            <span>Villa</span>
                                                        </Link>
                                                    </li>
                                                    <li className="date-icon">
                                                        <div className="post-author">
                                                            <div className="post-author-img">
                                                                <ImageWithBasePath
                                                                    src="assets/img/profiles/avatar-02.jpg"
                                                                    alt="author"
                                                                />
                                                            </div>
                                                            <Link to="#">
                                                                {" "}
                                                                <span>Francis </span>
                                                            </Link>
                                                        </div>
                                                        <i className="fa-solid fa-calendar-days" />{" "}
                                                        <span>Feb 8, 2023</span>
                                                    </li>
                                                </ul>
                                            </div>
                                            <h3 className="blog-title">
                                                <Link to={routes.blogDetails}>
                                                    How to achieve financial independence
                                                </Link>
                                            </h3>
                                            <p className="blog-description border-0 mb-0 pb-0">
                                                Omnis velit quia. Perspiciatis et cupiditate. Voluptatum
                                                beatae asperiores dolor magnam fuga. Sed fuga est harum quo
                                                nesciunt sint. Optio veniam...Omnis velit quia. Perspiciatis
                                                et cupiditate. Voluptatum beatae..
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div className="col-lg-12 col-md-12 d-lg-flex">
                                    <div className="blog grid-blog">
                                        <div className="blog-image-list">
                                            <Link to={routes.blogDetails}>
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    src="assets/img/blog/blog-list-03.jpg"
                                                    alt='img'
                                                />
                                            </Link>
                                        </div>
                                        <div className="blog-content">
                                            <div className="blog-list-date">
                                                <ul className="meta-item-list">
                                                    <li className="blog-category mb-0">
                                                        <Link to="#">
                                                            <span>House</span>
                                                        </Link>
                                                    </li>
                                                    <li className="date-icon">
                                                        <div className="post-author">
                                                            <div className="post-author-img">
                                                                <ImageWithBasePath
                                                                    src="assets/img/profiles/avatar-03.jpg"
                                                                    alt="author"
                                                                />
                                                            </div>
                                                            <Link to="#">
                                                                {" "}
                                                                <span> Eric Krok </span>
                                                            </Link>
                                                        </div>
                                                        <i className="fa-solid fa-calendar-days" />{" "}
                                                        <span>Feb 9, 2023</span>
                                                    </li>
                                                </ul>
                                            </div>
                                            <h3 className="blog-title">
                                                <Link to={routes.blogDetails}>
                                                    Learn how real estate really shapes our future
                                                </Link>
                                            </h3>
                                            <p className="blog-description border-0 mb-0 pb-0">
                                                There are many variations of passages of lorem ipsum
                                                available, but the majority have...
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {/* Pagination */}
                            <div className="grid-pagination">
                                <ul className="pagination justify-content-center">
                                    <li className="page-item prev">
                                        <Link className="page-link" to="#">
                                            <i className="fa-solid fa-arrow-left" /> Prev
                                        </Link>
                                    </li>
                                    <li className="page-item">
                                        <Link className="page-link" to="#">
                                            1
                                        </Link>
                                    </li>
                                    <li className="page-item active">
                                        <Link className="page-link" to="#">
                                            2
                                        </Link>
                                    </li>
                                    <li className="page-item">
                                        <Link className="page-link" to="#">
                                            3
                                        </Link>
                                    </li>
                                    <li className="page-item">
                                        <Link className="page-link" to="#">
                                            4
                                        </Link>
                                    </li>
                                    <li className="page-item next">
                                        <Link className="page-link" to="#">
                                            Next <i className="fa-solid fa-arrow-right" />
                                        </Link>
                                    </li>
                                </ul>
                            </div>
                            {/* /Pagination */}
                        </div>
                        <div className="col-lg-4 theiaStickySidebar">
                            <div className='stickybar'>
                                <div className="rightsidebar">
                                    <div className="card">
                                        <h4>Filter</h4>
                                        <div className="filter-content looking-input form-group mb-0">
                                            <input
                                                type="text"
                                                className="form-control"
                                                placeholder="Search"
                                            />
                                        </div>
                                    </div>
                                    <div className="card">
                                        <h4>Categories</h4>
                                        <ul className="blogcategories-list">
                                            <li>
                                                <Link to="#">Property</Link>
                                            </li>
                                            <li>
                                                <Link to="#">Villa</Link>
                                            </li>
                                            <li>
                                                <Link to="#">House</Link>
                                            </li>
                                            <li>
                                                <Link to="#">Guest House</Link>
                                            </li>
                                            <li>
                                                <Link to="#">Factory</Link>
                                            </li>
                                            <li>
                                                <Link to="#">Godown</Link>
                                            </li>
                                        </ul>
                                    </div>
                                    <div className="card">
                                        <h4>Top Article</h4>
                                        <div className="article">
                                            <div className="article-blog">
                                                <Link to={routes.blogDetails}>
                                                    <ImageWithBasePath
                                                        className="img-fluid"
                                                        src="assets/img/blog/blog-7.jpg"
                                                        alt="Blog"
                                                    />
                                                </Link>
                                            </div>
                                            <div className="article-content">
                                                <h5>
                                                    <Link to={routes.blogDetails}>Great Business Tips in 2023</Link>
                                                </h5>
                                                <div className="article-date">
                                                    <i className="fa-solid fa-calendar-days" />
                                                    <span>Jan 6, 2023</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="article">
                                            <div className="article-blog">
                                                <Link to={routes.blogDetails}>
                                                    <ImageWithBasePath
                                                        className="img-fluid"
                                                        src="assets/img/blog/blog-8.jpg"
                                                        alt="Blog"
                                                    />
                                                </Link>
                                            </div>
                                            <div className="article-content">
                                                <h5>
                                                    <Link to={routes.blogDetails}>
                                                        Excited News About Buildings.
                                                    </Link>
                                                </h5>
                                                <div className="article-date">
                                                    <i className="fa-solid fa-calendar-days" />
                                                    <span>Feb 5, 2023</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="article">
                                            <div className="article-blog">
                                                <Link to={routes.blogDetails}>
                                                    <ImageWithBasePath
                                                        className="img-fluid"
                                                        src="assets/img/blog/blog-9.jpg"
                                                        alt="Blog"
                                                    />
                                                </Link>
                                            </div>
                                            <div className="article-content">
                                                <h5>
                                                    <Link to={routes.blogDetails}>
                                                        8 Amazing Tricks About Build Dream..
                                                    </Link>
                                                </h5>
                                                <div className="article-date">
                                                    <i className="fa-solid fa-calendar-days" />
                                                    <span>October 6, 2022</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Blog Grid*/}
        </div>
    )
}

export default BlogList
