// angular/src/app/feature-module/authentication/reset-password/reset-password.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../shared/routes/routes';

@Component({
  selector: 'app-reset-password',
  templateUrl: './reset-password.component.html',
  styleUrl: './reset-password.component.scss'
})
export class ResetPasswordComponent {
  public routes = routes
  public show_password = true;
  togglePassword() {
    this.show_password = !this.show_password;
  }
}

<div class="container">
  <!-- Header -->
  <header class="log-header">
    <a [routerLink]="routes.home"
      ><img class="img-fluid logo-dark" src="assets/img/logo.svg" alt="Logo"
    /></a>
  </header>
  <!-- /Header -->

  <div class="login-wrapper">
    <div class="loginbox">
      <div class="login-auth">
        <div class="login-auth-wrap">
          <div class="sign-group">
            <a [routerLink]="routes.home" class="btn sign-up"
              ><span
                ><i
                  class="fe feather icon-corner-down-left"
                  aria-hidden="true"
                ></i
              ></span>
              Back To Home</a
            >
          </div>
          <h1>Reset Password</h1>
          <form>
            <div class="form-group">
              <label for="Password" class="form-label">Password <span>*</span></label>
              <div class="pass-group">
                <input
                  type="password"
                  class="form-control pass-input"
                  placeholder="Enter Password"
                  [type]="show_password ? 'password' : 'text'"
                />
                <span
                  [ngClass]="
                    show_password === true
                      ? 'fas fa-eye-slash toggle-password'
                      : 'fas fa-eye toggle-password'
                  "
                  (click)="togglePassword()"
                  (keydown.enter)="togglePassword()"
                  tabindex="0"
                  role="button"
                ></span>
              </div>
            </div>
            <div class="form-group">
              <label for="Confirm Password" class="form-label">Confirm Password <span>*</span></label>
              <div class="pass-group">
                <input
                  type="password"
                  class="form-control"
                  placeholder="Enter Confirm Password"
                />
              </div>
            </div>
            <div class="form-group">
              <label class="custom_check mt-0 mb-0"
                ><span>Remember me</span>
                <input type="checkbox" name="remeber" />
                <span class="checkmark"></span>
              </label>
            </div>
            <a
              [routerLink]="routes.login"
              class="btn btn-outline-light w-100 btn-size"
              >Reset</a
            >
            <div class="text-center dont-have">
              Already have login ? <a [routerLink]="routes.register">Sign In</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

// react/src/feature-module/pages/authentication/resetPassword.tsx
import React from "react";
import { Link } from "react-router-dom";
import { all_routes } from "../../router/all_routes";
import { CornerDownLeft } from "react-feather";

const ResetPassword = () => {
    const routes = all_routes;
  return (
    <div className="login-body">
      <div className="container">
        {/* Header */}
        <header className="log-header">
          <Link to={routes.home}>
            <img
              className="img-fluid logo-dark"
              src="assets/img/logo.svg"
              alt="Logo"
            />
          </Link>
        </header>
        {/* /Header */}
        <div className="login-wrapper">
          <div className="loginbox">
            <div className="login-auth">
              <div className="login-auth-wrap">
                <div className="sign-group">
                  <Link to={routes.home} className="btn sign-up">
                    <span>
                    <CornerDownLeft size={15} className='me-1'/>
                    </span>{" "}
                    Back To Home
                  </Link>
                </div>
                <h1>Reset Password</h1>
                <form >
                  <div className="form-group">
                    <label className="form-label">
                      Password <span>*</span>
                    </label>
                    <div className="pass-group">
                      <input
                        type="password"
                        className="form-control pass-input"
                        placeholder="Enter Password"
                      />
                      <span className="fas fa-eye toggle-password" />
                    </div>
                  </div>
                  <div className="form-group">
                    <label className="form-label">
                      Confirm Password <span>*</span>
                    </label>
                    <div className="pass-group">
                      <input
                        type="password"
                        className="form-control"
                        placeholder="Enter Confirm Password"
                      />
                    </div>
                  </div>
                  <div className="form-group">
                    <label className="custom_check mt-0 mb-0">
                      <span>Remember me</span>
                      <input type="checkbox" name="remeber" />
                      <span className="checkmark" />
                    </label>
                  </div>
                  <Link
                    to={routes.login}
                    className="btn btn-outline-light w-100 btn-size"
                  >
                    Reset
                  </Link>
                  <div className="text-center dont-have">
                    Already have login ? <Link to={routes.register}>Sign In</Link>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResetPassword;
