// react/src/feature-module/pages/gallery/index.tsx
/* eslint-disable @typescript-eslint/no-unused-vars */
import React, { useEffect, useState } from "react";
import BreadCrumb from "../../../core/common/breadCrumb";

import "aos/dist/aos.css";
import AOS from "aos";
import ImageWithBasePath from "../../../core/img";
import Lightbox from "yet-another-react-lightbox";
import "yet-another-react-lightbox/styles.css";
import { Link } from "react-router-dom";

const Gallery = () => {
  const [open, setOpen] = React.useState(false);
  
  
  useEffect(() => {
    AOS.init({ duration: 1200, once: true });
  }, []);

  return (
    <div>
      <>
        {/* Breadcrumb */}
        <BreadCrumb title="Gallery" pageTitle="Home" />
        {/* Breadcrumb */}
        <>
          <>
            {/* Gallery section*/}
            <div className="gallery-section">
              <div className="container">
                <div className="row">
                  <Lightbox
                    open={open}
                    close={() => setOpen(false)}
                    slides={[
                      { src: "/react/assets/img/gallery/gallery-01.jpg" },
                      { src: "/react/assets/img/gallery/gallery-02.jpg" },
                      { src: "/react/assets/img/gallery/gallery-03.jpg" },
                      { src: "/react/assets/img/gallery/gallery-04.jpg" },
                      { src: "/react/assets/img/gallery/gallery-05.jpg" },
                      { src: "/react/assets/img/gallery/gallery-06.jpg" },
                      { src: "/react/assets/img/gallery/gallery-07.jpg" },
                      { src: "/react/assets/img/gallery/gallery-08.jpg" },
                      { src: "/react/assets/img/gallery/gallery-09.jpg" },
                      { src: "/react/assets/img/gallery/gallery-10.jpg" },
                    ]}
                  />
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                         to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid" 
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-01.jpg"
                        />
                      </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-02.jpg"
                        />
                      </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-03.jpg"
                        />
                      </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-04.jpg"
                        />
                      </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-05.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-06.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-07.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-08.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-09.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-10.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-11.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-12.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-13.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-14.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-15.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-16.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-17.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                  <div
                    className="col-lg-4 col-md-6 col-sm-12 aos"
                    data-aos="fade-down"
                  >
                    <div className="gallery-widget">
                      <Link
                        to="#"
                        data-fancybox="gallery"
                        onClick={() => setOpen(true)}
                      >
                        <ImageWithBasePath
                          className="img-fluid"
                          alt="Image"
                          src="assets/img/gallery/gallery-thum-18.jpg"
                        />
                     </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Gallery section*/}
          </>
        </>
      </>
    </div>
  );
};

export default Gallery;

// angular/src/app/feature-module/pages/gallery/gallery.component.ts
import { Component, OnInit } from '@angular/core';
import { routes } from '../../../shared/routes/routes';
import lgZoom from 'lightgallery/plugins/zoom';
import { BeforeSlideDetail } from 'lightgallery/lg-events';
import lgThumbnail from 'lightgallery/plugins/thumbnail';
import * as AOS from 'aos';

@Component({
  selector: 'app-gallery',
  templateUrl: './gallery.component.html',
  styleUrl: './gallery.component.scss',
}) 
export class GalleryComponent implements OnInit {
  public routes = routes;
  settings = {
    counter: false,
    plugins: [lgZoom, lgThumbnail],
  };
  onBeforeSlide = (detail: BeforeSlideDetail): void => {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { index, prevIndex } = detail;
  };
  ngOnInit() {
    AOS.init({ disable: 'mobile', duration: 1200, once: true });
  }
}

 <!-- Breadcrumb -->
 <div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Gallery</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink] = "routes.home">Home </a></li>
                    <li>Gallery</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" alt="Line Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->		

<!-- Gallery section-->
<div class="gallery-section"> 
    <div class="container">
        <lightgallery [settings]="settings" [onBeforeSlide]="onBeforeSlide" class="row">
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down" data-src="assets/img/gallery/gallery-01.jpg" data-responsive="assets/img/gallery/gallery-01.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-01.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-01.jpg">
                    </a> 
                </div>					
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-02.jpg" data-responsive="assets/img/gallery/gallery-02.jpg">								
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-02.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-02.jpg">
                    </a>											
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-03.jpg" data-responsive="assets/img/gallery/gallery-03.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-03.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-03.jpg">
                    </a>											
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-04.jpg" data-responsive="assets/img/gallery/gallery-04.jpg">					
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-04.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-04.jpg">
                    </a>											
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-05.jpg" data-responsive="assets/img/gallery/gallery-05.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-05.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-05.jpg">
                    </a>											
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-06.jpg" data-responsive="assets/img/gallery/gallery-06.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-06.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-06.jpg">
                    </a>											
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-07.jpg" data-responsive="assets/img/gallery/gallery-07.jpg">					
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-07.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-07.jpg">
                    </a>											
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-08.jpg" data-responsive="assets/img/gallery/gallery-08.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-08.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-08.jpg">
                    </a>											
                </div>									
            </div>	
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-09.jpg" data-responsive="assets/img/gallery/gallery-09.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-09.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-09.jpg">
                    </a>											
                </div>									
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-10.jpg" data-responsive="assets/img/gallery/gallery-10.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-10.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-10.jpg">
                    </a>											
                </div>									
            </div>	
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-11.jpg" data-responsive="assets/img/gallery/gallery-11.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-11.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-11.jpg">
                    </a>											
                </div>									
            </div>	
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-12.jpg" data-responsive="assets/img/gallery/gallery-12.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-12.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-12.jpg">
                    </a>											
                </div>									
            </div>	
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-13.jpg" data-responsive="assets/img/gallery/gallery-13.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-13.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-13.jpg">
                    </a>											
                </div>									
            </div>	
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-14.jpg" data-responsive="assets/img/gallery/gallery-14.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-14.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-14.jpg">
                    </a>											
                </div>									
            </div>	
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-15.jpg" data-responsive="assets/img/gallery/gallery-15.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-15.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-15.jpg">
                    </a>											
                </div>									
            </div>	
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-16.jpg" data-responsive="assets/img/gallery/gallery-16.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-16.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-16.jpg">
                    </a>											
                </div>									
            </div>	
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-17.jpg" data-responsive="assets/img/gallery/gallery-17.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-17.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-17.jpg">
                    </a>											
                </div>									
            </div>	
            <div class="col-lg-4 col-md-6 col-sm-12 aos" data-aos="fade-down"  data-src="assets/img/gallery/gallery-18.jpg" data-responsive="assets/img/gallery/gallery-18.jpg">
                <div class="gallery-widget">
                    <a href="assets/img/gallery/gallery-18.jpg" data-fancybox="gallery2">
                        <img class="img-fluid" alt="Image" src="assets/img/gallery/gallery-thum-18.jpg">
                    </a>											
                </div>									
            </div>	
        </lightgallery>
    </div> 
</div> 					  
<!-- /Gallery section-->
