// react/src/feature-module/pages/authentication/forgotPassword.tsx
import React from "react";
import { Link } from "react-router-dom";
import { all_routes } from "../../router/all_routes";
import { CornerDownLeft } from "react-feather";

const ForgotPassword = () => {
    const routes = all_routes;
  return (
    <div className="login-body">
      <div className="container">
        {/* Header */}
        <header className="log-header">
          <Link to={routes.home}>
            <img
              className="img-fluid logo-dark"
              src="assets/img/logo.svg"
              alt="Logo"
            />
          </Link>
        </header>
        {/* /Header */}
        <div className="login-wrapper">
          <div className="loginbox">
            <div className="login-auth">
              <div className="login-auth-wrap">
                <div className="sign-group">
                  <Link to={routes.home} className="btn sign-up">
                    <span>
                     
                       <CornerDownLeft size={15} className='me-1'/>
                    </span>{" "}
                    Back To Home
                  </Link>
                </div>
                <h1>Forgot Password</h1>
                <form>
                  <div className="form-group">
                    <label className="form-label">
                      Email <span>*</span>
                    </label>
                    <input
                      type="email"
                      className="form-control"
                      placeholder="Enter Email"
                    />
                  </div>
                  <Link
                    to={routes.restPassword}
                    className="btn btn-outline-light w-100 btn-size"
                  >
                    Sign Up
                  </Link>
                  <div className="text-center dont-have">
                    Remember login ? <Link to={routes.login}>Sign In</Link>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ForgotPassword;

// angular/src/app/feature-module/authentication/forgot-password/forgot-password.component.ts
import { Component, OnDestroy, Renderer2 } from '@angular/core';
import { CommonService } from '../../../shared/common/common.service';
import { routes } from '../../../shared/routes/routes';
import { Router } from '@angular/router';

@Component({
  selector: 'app-forgot-password',
  templateUrl: './forgot-password.component.html',
  styleUrl: './forgot-password.component.scss'
})
export class ForgotPasswordComponent implements OnDestroy {
  public routes = routes;
  base = '';
  page = '';
  last = '';

  constructor(
    private common: CommonService,
    private renderer: Renderer2,
    private router: Router
  ) {
    this.common.base.subscribe((res: string) => {
      this.base = res;
    });
    this.common.page.subscribe((res: string) => {
      this.page = res;
    });
    this.common.last.subscribe((res: string) => {
      this.last = res;
    });
    if(this.base == 'forgot-password') {
      this.renderer.addClass(document.body, 'login-body');
    }
  }
  ngOnDestroy(): void {
    this.renderer.removeClass(document.body, 'login-body');
  }
  public navigate(){
    this.router.navigate([routes.rentPropertyGrid])
  }
}

<div class="container">
    <!-- Header -->
    <header class="log-header">
        <a [routerLink]="routes.home"><img class="img-fluid logo-dark" src="assets/img/logo.svg" alt="Logo"></a>
    </header>
    <!-- /Header -->

    <div class="login-wrapper">
        <div class="loginbox">
            <div class="login-auth">
                <div class="login-auth-wrap">
                    <div class="sign-group">
                        <a [routerLink]="routes.home" class="btn sign-up"><span><i
                                    class="fe feather icon-corner-down-left" aria-hidden="true"></i></span> Back To
                            Home</a>
                    </div>
                    <h1>Forgot Password</h1>
                    <form>
                        <div class="form-group">
                            <label for="email" class="form-label">Email <span>*</span></label>
                            <input type="email" class="form-control" placeholder="Enter Email">
                        </div>
                        <a [routerLink] = "routes.resetPassword" class="btn btn-outline-light w-100 btn-size">Sign Up</a>
                        <div class="text-center dont-have">Remember login ? <a [routerLink]="routes.login">Sign In</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
