// angular/src/app/feature-module/listing/rental-orders/rental-order/rental-order.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../../shared/routes/routes';

@Component({
  selector: 'app-rental-order',
  templateUrl: './rental-order.component.html',
  styleUrl: './rental-order.component.scss'
})
export class RentalOrderComponent {
  public routes = routes

}

  <!-- Breadcrumb -->
  <div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Rental Booking</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink]="routes.home">Home </a></li>
                    <li>Rental Booking</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" alt="Line Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->

<!-- Detail View Section -->
<section class="content inner-content bg-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="success-div">
                    <span><i class="bx bx-check-circle me-1"></i>Modern apartment in the city centre is available for rental</span>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="details-div">
                    <div class="details-div-content">
                        <h5>Details</h5>
                        <p>Modern Apartment in the city centre</p>
                        <h5>Location </h5>
                        <p class="mb-0">318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                    </div>
                    <div class="details-div-price">
                        <h5>Booking Amount</h5>
                        <h6>$300 <span>/ Day</span></h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="details-time">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="arrival-div">
                                <h5>Arrival Time</h5>
                                <ul>
                                    <li>
                                        <input type="radio" id="radio1" name="Arrival">
                                        <label for="radio1">Tue<span>21</span>Feb</label>
                                    </li>
                                    <li>
                                        <input type="radio" id="radio2" name="Arrival" checked>
                                        <label for="radio2">Wed<span>22</span>Feb</label>
                                    </li>
                                    <li>
                                        <input type="radio" id="radio3" name="Arrival">
                                        <label for="radio3">Thur<span>23</span>Feb</label>
                                    </li>
                                    <li>
                                        <input type="radio" id="radio4" name="Arrival">
                                        <label for="radio4">Feb<span>24</span>Feb</label>
                                    </li>
                                    <li>
                                        <input type="radio" id="radio5" name="Arrival">
                                        <label for="radio5">Sat<span>25</span>Feb</label>
                                    </li>
                                </ul>
                            </div>	
                            <div class="review-form mb-0">
                                
                                <mat-select class="custom-mat-select" placeholder="Select">
                                    <mat-option value="0">Select Time</mat-option>
                                    <mat-option value="1">10 AM - 12 PM</mat-option>
                                    <mat-option value="2">12 PM - 2 PM</mat-option>
                                    <mat-option value="3">02 PM - 04 PM</mat-option>
                                </mat-select>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="arrival-div arrival-dept">
                                <h5>Departure Time</h5>
                                <ul>
                                    <li>
                                        <input type="radio" id="Departure1" name="Departure">
                                        <label for="Departure1">Tue<span>21</span>Feb</label>
                                    </li>
                                    <li>
                                        <input type="radio" id="Departure2" name="Departure" checked>
                                        <label for="Departure2">Wed<span>22</span>Feb</label>
                                    </li>
                                    <li>
                                        <input type="radio" id="Departure3" name="Departure">
                                        <label for="Departure3">Thur<span>23</span>Feb</label>
                                    </li>
                                    <li>
                                        <input type="radio" id="Departure4" name="Departure">
                                        <label for="Departure4">Feb<span>24</span>Feb</label>
                                    </li>
                                    <li>
                                        <input type="radio" id="Departure5" name="Departure">
                                        <label for="Departure5">Sat<span>25</span>Feb</label>
                                    </li>
                                </ul>
                            </div>	
                            <div class="review-form mb-0">
                                <mat-select class="custom-mat-select" placeholder="Select">
                                    <mat-option value="0">Select Time</mat-option>
                                    <mat-option value="1">10 AM - 12 PM</mat-option>
                                    <mat-option value="2">12 PM - 2 PM</mat-option>
                                    <mat-option value="3">02 PM - 04 PM</mat-option>
                                </mat-select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="booking-details">
                    <div class="row">
                        <div class="col-lg-12">
                            <h4>Booking Details</h4>
                            <ul>
                                <li>
                                    <h5>Arrival Time</h5>
                                    <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                                </li>
                                <li>
                                    <h5>Departure Time</h5>
                                    <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="booking-details-price">
                    <div class="row">
                        <div class="col-lg-12">
                            <ul>
                                <li>
                                    <h5>Booking Price </h5>
                                    <h6>$300</h6>
                                </li>
                                <li>
                                    <h5>Service Charge</h5>
                                    <h6>$10</h6>
                                </li>
                                <li>
                                    <h5>Tax</h5>
                                    <h6>$5</h6>
                                </li>
                            </ul>
                            <ul class="booking-details-total">
                                <li>
                                    <h5>Grand Total</h5>
                                    <h6>$315</h6>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="booking-details-btn">
                    <a href="javascript:void(0);" class="btn btn-lightred me-2">Previous</a>
                    <a [routerLink] = "routes.rentalOrderStep1" class="btn btn-primary">Go to Details</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Detail View Section -->

// react/src/feature-module/listing/rentalOrder.tsx
import React from "react";
import BreadCrumb from "../../core/common/breadCrumb";
import { Link } from "react-router-dom";
import { all_routes } from "../router/all_routes";
import Select from 'react-select';
import { customStyles, sortByTime1,  } from "../../core/common/select";

const RentalOrder = () => {
  const routes = all_routes;
  return (
    <div>
      <>
        {/* Breadcrumb */}
        <BreadCrumb title="Rental Booking" pageTitle="Home" />
        {/* Breadcrumb */}
        {/* Detail View Section */}
        <section className="content inner-content bg-white">
          <div className="container">
            <div className="row">
              <div className="col-lg-12">
                <div className="success-div">
                  <span>
                    <i className="bx bx-check-circle me-1" />
                    Modern apartment in the city centre is available for rental
                  </span>
                </div>
              </div>
              <div className="col-lg-12">
                <div className="details-div">
                  <div className="details-div-content">
                    <h5>Details</h5>
                    <p>Modern Apartment in the city centre</p>
                    <h5>Location </h5>
                    <p className="mb-0">
                      318-330 S Oakley Blvd, Chicago, IL 60612, USA
                    </p>
                  </div>
                  <div className="details-div-price">
                    <h5>Booking Amount</h5>
                    <h6>
                      $300 <span>/ Day</span>
                    </h6>
                  </div>
                </div>
              </div>
              <div className="col-lg-12">
                <div className="details-time">
                  <div className="row">
                    <div className="col-lg-6">
                      <div className="arrival-div">
                        <h5>Arrival Time</h5>
                        <ul>
                          <li>
                            <input type="radio" id="radio1" name="Arrival" />
                            <label htmlFor="radio1">
                              Tue<span>21</span>Feb
                            </label>
                          </li>
                          <li>
                            <input type="radio" id="radio2" name="Arrival" />
                            <label htmlFor="radio2">
                              Wed<span>22</span>Feb
                            </label>
                          </li>
                          <li>
                            <input type="radio" id="radio3" name="Arrival" />
                            <label htmlFor="radio3">
                              Thur<span>23</span>Feb
                            </label>
                          </li>
                          <li>
                            <input type="radio" id="radio4" name="Arrival" />
                            <label htmlFor="radio4">
                              Feb<span>24</span>Feb
                            </label>
                          </li>
                          <li>
                            <input type="radio" id="radio5" name="Arrival" />
                            <label htmlFor="radio5">
                              Sat<span>25</span>Feb
                            </label>
                          </li>
                        </ul>
                      </div>
                      <div className="review-form mb-0">
                      <Select options={sortByTime1} defaultValue={sortByTime1[0]} className="select" styles={customStyles} />
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="arrival-div arrival-dept">
                        <h5>Departure Time</h5>
                        <ul>
                          <li>
                            <input
                              type="radio"
                              id="Departure1"
                              name="Departure"
                            />
                            <label htmlFor="Departure1">
                              Tue<span>21</span>Feb
                            </label>
                          </li>
                          <li>
                            <input
                              type="radio"
                              id="Departure2"
                              name="Departure"
                            />
                            <label htmlFor="Departure2">
                              Wed<span>22</span>Feb
                            </label>
                          </li>
                          <li>
                            <input
                              type="radio"
                              id="Departure3"
                              name="Departure"
                            />
                            <label htmlFor="Departure3">
                              Thur<span>23</span>Feb
                            </label>
                          </li>
                          <li>
                            <input
                              type="radio"
                              id="Departure4"
                              name="Departure"
                            />
                            <label htmlFor="Departure4">
                              Feb<span>24</span>Feb
                            </label>
                          </li>
                          <li>
                            <input
                              type="radio"
                              id="Departure5"
                              name="Departure"
                            />
                            <label htmlFor="Departure5">
                              Sat<span>25</span>Feb
                            </label>
                          </li>
                        </ul>
                      </div>
                      <div className="review-form mb-0">
                      <Select options={sortByTime1} defaultValue={sortByTime1[0]} className="select" styles={customStyles} />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-12">
                <div className="booking-details">
                  <div className="row">
                    <div className="col-lg-12">
                      <h4>Booking Details</h4>
                      <ul>
                        <li>
                          <h5>Arrival Time</h5>
                          <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                        </li>
                        <li>
                          <h5>Departure Time</h5>
                          <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-12">
                <div className="booking-details-price">
                  <div className="row">
                    <div className="col-lg-12">
                      <ul>
                        <li>
                          <h5>Booking Price </h5>
                          <h6>$300</h6>
                        </li>
                        <li>
                          <h5>Service Charge</h5>
                          <h6>$10</h6>
                        </li>
                        <li>
                          <h5>Tax</h5>
                          <h6>$5</h6>
                        </li>
                      </ul>
                      <ul className="booking-details-total">
                        <li>
                          <h5>Grand Total</h5>
                          <h6>$315</h6>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-12">
                <div className="booking-details-btn">
                  <Link to="#" className="btn btn-lightred me-2">
                    Previous
                  </Link>
                  <Link
                    to={routes.rentalOrderStep1}
                    className="btn btn-primary"
                  >
                    Go to Details
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* /Detail View Section */}
      </>
    </div>
  );
};

export default RentalOrder;
