// angular/src/app/feature-module/listing/rental-orders/rental-order-step3/rental-order-step3.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../../shared/routes/routes';

@Component({
  selector: 'app-rental-order-step3',
  templateUrl: './rental-order-step3.component.html',
  styleUrl: './rental-order-step3.component.scss'
})
export class RentalOrderStep3Component {
  public routes = routes;
}

 <!-- Breadcrumb -->
 <div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Rental Booking</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink] = "routes.home">Home </a></li>
                    <li>Rental Booking</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" alt="Line Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->

<!-- Detail View Section -->
<section class="content inner-content bg-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="details-div">
                    <div class="details-div-content">
                        <h5>Details</h5>
                        <p>Modern Apartment in the city centre</p>
                        <h5>Location </h5>
                        <p class="mb-0">318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                    </div>
                    <div class="details-div-price">
                        <h5>Booking Amount</h5>
                        <h6>$300 <span>/ Day</span></h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="booking-details mb-0 pb-lg-3 pb-0">
                    <h4>Choose Payment Method</h4>
                    <div class="payment-icon">
                        <ul>
                            <li>
                                <span><img src="assets/img/payment/paypal.png" alt="img"></span>
                            </li>
                            <li>
                                <span><img src="assets/img/payment/stripe.png" alt="img"></span>
                            </li>
                            <li class="active">
                                <span><img src="assets/img/payment/card.png" alt="img"></span>
                            </li>
                            <li class="mb-0">
                                <span><img src="assets/img/payment/wallet.png" alt="img"></span>
                            </li>
                        </ul>
                    </div>
                    <h4>Add New Card</h4>
                    <div class="row">
                        <div class="col-lg-6 col-sm-12">
                            <div class="review-form">
                                <label for="Card Number">Card Number</label>
                                <input type="text" class="form-control" placeholder="+1 3940 9404">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12">
                            <div class="review-form">
                                <label for="Card Holder Name">Card Holder Name<span class="manitory">*</span></label>
                                <input type="text" class="form-control" placeholder="Roudrigez">
                            </div>
                        </div>
                        <div class="col-lg-4 col-sm-12">
                            <div class="review-form">
                                <label for="Select Date">Select Date</label>
                                <input type="text" class="form-control datetimepicker" placeholder="Select Date">
                            </div>
                        </div>
                        <div class="col-lg-4 col-sm-12">
                            <div class="review-form">
                                <label for="review">&nbsp;</label>
                                <mat-select class="custom-mat-select" placeholder="Select Year">
                                    <mat-option value="2012">2012</mat-option>
                                    <mat-option value="2013">2013</mat-option>
                                    <mat-option value="2014">2014</mat-option>
                                    <mat-option value="2015">2015</mat-option>
                                </mat-select>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="review-form">
                                <label for="cvv">CVV</label>
                                <input type="text" class="form-control" placeholder="Enter Security Number">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="booking-details-btn">
                    <a [routerLink] = "routes.rentalOrder" class="btn btn-lightred me-2">Go Back</a>
                    <a href="javascript:void(0);" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#success">Book Now</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Detail View Section -->

// react/src/feature-module/listing/rentalOrderStep3.tsx
import React, { useState } from 'react'
import BreadCrumb from '../../core/common/breadCrumb'
import { Link } from 'react-router-dom'
import ImageWithBasePath from '../../core/img'
import { all_routes } from '../router/all_routes'

const RentalOrderStep3 = () => {
    const routes = all_routes
    const [activeIndex, setActiveIndex] = useState(1);

    const handleClick = (index: any) => {
        setActiveIndex(index);
    };

    return (
        <>
            {/* Breadcrumb */}
            <BreadCrumb title="Rental Booking" pageTitle="Home" />
            {/* Breadcrumb */}
            {/* Detail View Section */}
            <section className="content inner-content bg-white">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-12">
                            <div className="details-div">
                                <div className="details-div-content">
                                    <h5>Details</h5>
                                    <p>Modern Apartment in the city centre</p>
                                    <h5>Location </h5>
                                    <p className="mb-0">
                                        318-330 S Oakley Blvd, Chicago, IL 60612, USA
                                    </p>
                                </div>
                                <div className="details-div-price">
                                    <h5>Booking Amount</h5>
                                    <h6>
                                        $300 <span>/ Day</span>
                                    </h6>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-12">
                            <div className="booking-details mb-0 pb-lg-3 pb-0">
                                <h4>Choose Payment Method</h4>
                                <div className="payment-icon">
                                    <ul>
                                        <li className={activeIndex === 0 ? "active" : ""} onClick={() => handleClick(0)}>

                                            <span>
                                                <ImageWithBasePath src="assets/img/payment/paypal.png" alt="img" />
                                            </span>
                                        </li>
                                        <li>
                                            <span>
                                                <ImageWithBasePath src="assets/img/payment/stripe.png" alt="img" />
                                            </span>
                                        </li>
                                        <li className="active">
                                            <span>
                                                <ImageWithBasePath src="assets/img/payment/card.png" alt="img" />
                                            </span>
                                        </li>
                                        <li className="mb-0">
                                            <span>
                                                <ImageWithBasePath src="assets/img/payment/wallet.png" alt="img" />
                                            </span>
                                        </li>
                                    </ul>
                                </div>
                                <h4>Add New Card</h4>
                                <div className="row">
                                    <div className="col-lg-6 col-sm-12">
                                        <div className="review-form">
                                            <label>Card Number</label>
                                            <input
                                                type="text"
                                                className="form-control"
                                                placeholder="+1 3940 9404"
                                            />
                                        </div>
                                    </div>
                                    <div className="col-lg-6 col-sm-12">
                                        <div className="review-form">
                                            <label>
                                                Card Holder Name<span className="manitory">*</span>
                                            </label>
                                            <input
                                                type="text"
                                                className="form-control"
                                                placeholder="Roudrigez"
                                            />
                                        </div>
                                    </div>
                                    <div className="col-lg-4 col-sm-12">
                                        <div className="review-form">
                                            <label>Select Date</label>
                                            <input
                                                type="text"
                                                className="form-control datetimepicker"
                                                placeholder="Select Date"
                                            />
                                        </div>
                                    </div>
                                    <div className="col-lg-4 col-sm-12">
                                        <div className="review-form">
                                            <label>&nbsp;</label>
                                            <select className="form-control select">
                                                <option>Select Year</option>
                                                <option>2012</option>
                                                <option>2013</option>
                                                <option>2014</option>
                                                <option>2015</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div className="col-lg-4">
                                        <div className="review-form">
                                            <label>CVV</label>
                                            <input
                                                type="text"
                                                className="form-control"
                                                placeholder="Enter Security Number"
                                            />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-12">
                            <div className="booking-details-btn">
                                <Link to={routes.rentalOrder} className="btn btn-lightred me-2">
                                    Go Back
                                </Link>
                                <Link
                                    to="#"
                                    className="btn btn-primary"
                                    data-bs-toggle="modal"
                                    data-bs-target="#success"
                                >
                                    Book Now
                                </Link>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {/* /Detail View Section */}
        </>

    )
}

export default RentalOrderStep3
