// angular/src/app/feature-module/listing/rental-orders/rental-order-step1/rental-order-step1.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../../shared/routes/routes';

@Component({
  selector: 'app-rental-order-step1',
  templateUrl: './rental-order-step1.component.html',
  styleUrl: './rental-order-step1.component.scss'
})
export class RentalOrderStep1Component {
  public routes = routes;
}

<!-- Breadcrumb -->
<div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Rental Booking</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink] = "routes.home">Home </a></li>
                    <li>Rental Booking</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" alt="Line Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->

<!-- Detail View Section -->
<section class="content inner-content bg-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="success-div">
                    <span><i class="bx bx-check-circle me-1"></i>Modern apartment in the city centre is available for rental</span>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="details-div">
                    <div class="details-div-content">
                        <h5>Details</h5>
                        <p>Modern Apartment in the city centre</p>
                        <h5>Location </h5>
                        <p class="mb-0">318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                    </div>
                    <div class="details-div-price">
                        <h5>Booking Amount</h5>
                        <h6>$300 <span>/ Day</span></h6>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="booking-details">
                    <h4>Property Booking Details</h4>
                    <ul>
                        <li>
                            <h5>Arrival Time</h5>
                            <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                        </li>
                        <li>
                            <h5>Departure Time</h5>
                            <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="booking-details">
                    <h4>Booking Details</h4>
                    <ul>
                        <li>
                            <h5>Arrival Time</h5>
                            <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                        </li>
                        <li>
                            <h5>Departure Time</h5>
                            <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="booking-details mb-0">
                    <h4>Fill out this quick form</h4>
                    <div class="row">
                        <div class="col-lg-6 col-sm-12">
                            <div class="review-form">
                                <label for="Name">Name<span class="manitory">*</span></label>
                                <input type="text" class="form-control" placeholder="Enter Name">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12">
                            <div class="review-form">
                                <label for="Phone Number">Phone Number <span class="manitory">*</span></label>
                                <input type="text" class="form-control" placeholder="Enter Phone Number">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12">
                            <div class="review-form">
                                <label for="Email Address">Email Address</label>
                                <input type="text" class="form-control" placeholder="Enter Email">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12">
                            <div class="review-form">
                                <label for="Full Address">Full Address</label>
                                <input type="text" class="form-control" placeholder="Enter Address">
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="review-form mb-0">
                                <label for="Special Requests">Special Requests / Questions / Comments</label>
                                <textarea rows="5" placeholder="Enter Comments"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="booking-details-btn">
                    <a [routerLink] = "routes.rentalOrderStep1" class="btn btn-lightred me-2">Back to Booking Details</a>
                    <a [routerLink] = "routes.rentalOrderStep2" class="btn btn-primary">Go to Order Confirmation</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Detail View Section -->

// react/src/feature-module/listing/rentalOrderStep1.tsx
import React from 'react'
import { Link } from 'react-router-dom'
import BreadCrumb from '../../core/common/breadCrumb'
import { all_routes } from '../router/all_routes'

const   RentalOrderStep1 = () => {
  const routes = all_routes
  return (
    <>
  {/* Breadcrumb */}
  <BreadCrumb title="Rental Booking" pageTitle="Home" />
  {/* Breadcrumb */}
  {/* Detail View Section */}
  <section className="content inner-content bg-white">
    <div className="container">
      <div className="row">
        <div className="col-lg-12">
          <div className="success-div">
            <span>
              <i className="bx bx-check-circle me-1" />
              Modern apartment in the city centre is available for rental
            </span>
          </div>
        </div>
        <div className="col-lg-12">
          <div className="details-div">
            <div className="details-div-content">
              <h5>Details</h5>
              <p>Modern Apartment in the city centre</p>
              <h5>Location </h5>
              <p className="mb-0">
                318-330 S Oakley Blvd, Chicago, IL 60612, USA
              </p>
            </div>
            <div className="details-div-price">
              <h5>Booking Amount</h5>
              <h6>
                $300 <span>/ Day</span>
              </h6>
            </div>
          </div>
        </div>
        <div className="col-lg-12">
          <div className="booking-details">
            <h4>Property Booking Details</h4>
            <ul>
              <li>
                <h5>Arrival Time</h5>
                <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
              </li>
              <li>
                <h5>Departure Time</h5>
                <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
              </li>
            </ul>
          </div>
        </div>
        <div className="col-lg-12">
          <div className="booking-details">
            <h4>Booking Details</h4>
            <ul>
              <li>
                <h5>Arrival Time</h5>
                <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
              </li>
              <li>
                <h5>Departure Time</h5>
                <p>318-330 S Oakley Blvd, Chicago, IL 60612, USA</p>
              </li>
            </ul>
          </div>
        </div>
        <div className="col-lg-12">
          <div className="booking-details mb-0">
            <h4>Fill out this quick form</h4>
            <div className="row">
              <div className="col-lg-6 col-sm-12">
                <div className="review-form">
                  <label>
                    Name<span className="manitory">*</span>
                  </label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Enter Name"
                  />
                </div>
              </div>
              <div className="col-lg-6 col-sm-12">
                <div className="review-form">
                  <label>
                    Phone Number <span className="manitory">*</span>
                  </label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Enter Phone Number"
                  />
                </div>
              </div>
              <div className="col-lg-6 col-sm-12">
                <div className="review-form">
                  <label>Email Address</label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Enter Email"
                  />
                </div>
              </div>
              <div className="col-lg-6 col-sm-12">
                <div className="review-form">
                  <label>Full Address</label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Enter Address"
                  />
                </div>
              </div>
              <div className="col-lg-12">
                <div className="review-form mb-0">
                  <label>Special Requests / Questions / Comments</label>
                  <textarea
                    rows={5}
                    placeholder="Enter Comments"
                    defaultValue={""}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="col-lg-12">
          <div className="booking-details-btn">
            <Link to={routes.rentalOrderStep1} className="btn btn-lightred me-2">
              Back to Booking Details
            </Link>
            <Link to={routes.rentalOrderStep2} className="btn btn-primary">
              Go to Order Confirmation
            </Link>
          </div>
        </div>
      </div>
    </div>
  </section>
  {/* /Detail View Section */}
</>

  )
}

export default RentalOrderStep1
