// react/src/feature-module/contactUs/index.tsx
import React from 'react'
import BreadCrumb from '../../core/common/breadCrumb'
import { Link } from 'react-router-dom'
import ImageWithBasePath from '../../core/img'
import Select from 'react-select'
import { country, customStyles } from '../../core/common/select'
import { all_routes } from '../router/all_routes'
// import BreadCrumb from '../../core/common/breadCrumb'

const ContactUs = () => {
  const routes = all_routes
  return (
    <div>
        <>
  {/* Breadcrumb */}
  <BreadCrumb title="Contact Us" pageTitle="Home" />
  {/* Breadcrumb */}
  {/* Contact us */}
  <section className="section contact-section">
    <div className="container">
      <div className="contact-content">
        <div className="row align-items-center">
          <div className="col-lg-6">
            <div className="row">
              <div className="col-lg-12 d-flex">
                <div className="card">
                  <div className="card-body contact-info flex-fill">
                    <h3>Talk to Member of Sales Team</h3>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      Quisque quis ligula eu lectus vulputate porttitor sed
                      feugiat nunc. Mauris ac consectetur ante,
                    </p>
                    <Link
                      to="#"
                      className="btn-primary d-inline-block"
                    >
                      Contact Sales
                    </Link>
                  </div>
                </div>
              </div>
              <div className="col-lg-12 d-flex">
                <div className="card">
                  <div className="card-body contact-info flex-fill">
                    <h3>Product &amp; Account Support</h3>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      Quisque quis ligula eu lectus vulputate porttitor sed
                      feugiat nunc. Mauris ac consectetur ante,
                    </p>
                    <Link to={routes.faq} className="btn-primary d-inline-block">
                      Go to FAQ
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-lg-6">
            <ImageWithBasePath src="assets/img/contact.jpg" alt="Image" />
          </div>
        </div>
      </div>
    </div>
  </section>
  {/* /Contact us */}
  {/* Contact Info Details */}
  <section className="section contact-info-sec">
    <div className="container">
      <div className="row">
        <div className="col-lg-6">
          <form action="#">
            <div className="card">
              <div className="card-header">
                <h3>Get In Touch</h3>
              </div>
              <div className="card-body">
                <div className="row">
                  <div className="col-lg-12 col-12">
                    <div className="form-group">
                      <label>Your Name</label>
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Your Name"
                      />
                    </div>
                  </div>
                  <div className="col-lg-6 col-12">
                    <div className="form-group">
                      <label>Phone Number</label>
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Enter Number"
                      />
                    </div>
                  </div>
                  <div className="col-lg-6 col-12">
                    <div className="form-group">
                      <label>Email Address</label>
                      <input
                        type="email"
                        className="form-control"
                        placeholder="Enter Email"
                      />
                    </div>
                  </div>
                  <div className="col-lg-6 col-12">
                    <div className="form-group">
                      <label>Country</label>
                      <Select options={country} defaultValue={country[0]} className="select" styles={customStyles} />
                    </div>
                  </div>
                  <div className="col-lg-6 col-12">
                    <div className="form-group">
                      <label>Subject</label>
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Enter Subject"
                      />
                    </div>
                  </div>
                  <div className="col-md-12">
                    <div className="form-group">
                      <label>Description</label>
                      <textarea
                        className="form-control"
                        rows={14}
                        placeholder="Comments"
                        defaultValue={""}
                      />
                    </div>
                  </div>
                </div>
                <button type="submit" className="btn-primary">
                  Submit Enquiry
                </button>
              </div>
            </div>
          </form>
        </div>
        <div className="col-lg-6">
          <h3>Contact Details</h3>
          <div className="row">
            <div className="col-lg-12 d-flex">
              <div className="flex-fill">
                <div className="contact-info-details d-flex align-items-center">
                  <span>
                    <ImageWithBasePath src="assets/img/icons/phone.svg" alt="Image" />
                  </span>
                  <div>
                    <h4>Call Us At</h4>
                    <Link to="tel:+16398098393">+1 63980 98393</Link>,
                    <Link to="tel:+16398098393">+1 63980 98393</Link>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-lg-12 d-flex">
              <div className="flex-fill">
                <div className="contact-info-details d-flex align-items-center">
                  <span>
                    <ImageWithBasePath src="assets/img/icons/mail.svg" alt="Image" />
                  </span>
                  <div>
                    <h4>Email Us</h4>
                    <Link to="mailto:info@example.com">info@example.com</Link>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-lg-12 d-flex">
              <div className="flex-fill">
                <div className="contact-info-details d-flex align-items-center">
                  <span>
                    <ImageWithBasePath src="assets/img/icons/map-pin.svg" alt="Image" />
                  </span>
                  <div>
                    <h4>Location</h4>
                    <p>Jl. Surabaya Jaya, No.10, Surabaya United States</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="map-location">
            <h3>Find Us On</h3>
            <iframe
            title='Google Map'
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2967.8862835683544!2d-73.98256668525309!3d41.93829486962529!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89dd0ee3286615b7%3A0x42bfa96cc2ce4381!2s132%20Kingston%20St%2C%20Kingston%2C%20NY%2012401%2C%20USA!5e0!3m2!1sen!2sin!4v1670922579281!5m2!1sen!2sin"
              height={359}
            />
          </div>
        </div>
      </div>
    </div>
  </section>
  {/* /Contact Info Details */}
</>

    </div>
  )
}

export default ContactUs

// angular/src/app/feature-module/pages/contact-us/contact-us.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../shared/routes/routes';

@Component({
  selector: 'app-contact-us',
  templateUrl: './contact-us.component.html',
  styleUrl: './contact-us.component.scss'
})
export class ContactUsComponent {
  public routes = routes;
}

<!-- Breadcrumb -->
<div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Contact Us</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink] = "routes.home">Home </a></li>
                    <li>Contact Us</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" alt="Line Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->		


<!-- Contact us -->
<section class="section contact-section">
    <div class="container">
        <div class="contact-content">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="row">
                        <div class="col-lg-12 d-flex"> 
                            <div class="card">
                                <div class="card-body contact-info flex-fill">
                                    <h3>Talk to Member of Sales Team</h3>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis ligula eu lectus vulputate porttitor sed feugiat nunc. Mauris ac consectetur ante,</p>
                                    <a href="javascript:void(0);" class="btn-primary d-inline-block">Contact Sales</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 d-flex"> 
                            <div class="card">
                                <div class="card-body contact-info flex-fill">
                                    <h3>Product & Account Support</h3>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis ligula eu lectus vulputate porttitor sed feugiat nunc. Mauris ac consectetur ante,</p>
                                    <a [routerLink] = "routes.faq" class="btn-primary d-inline-block">Go to FAQ</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <img src="assets/img/contact.jpg" alt="Image">
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Contact us -->

<!-- Contact Info Details -->
<section class="section contact-info-sec">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <form action="#">     
                    <div class="card">
                        <div class="card-header">
                            <h3>Get In Touch</h3>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-12 col-12"> 
                                    <div class="form-group">
                                        <label for="Your Name">Your Name</label>
                                        <input type="text" class="form-control" placeholder="Your Name">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-12"> 
                                    <div class="form-group">
                                        <label for="Phone Number">Phone Number</label>
                                        <input type="text" class="form-control" placeholder="Enter Number">
                                    </div>
                                </div>
                                <div class="col-lg-6 col-12"> 
                                    <div class="form-group">
                                        <label for="Email Address">Email Address</label>
                                        <input type="email" class="form-control" placeholder="Enter Email">
                                    </div>
                                </div>		
                                <div class="col-lg-6 col-12"> 
                                    <div class="form-group">
                                        <label for="Country">Country</label>
                                        <mat-select class="custom-mat-select" placeholder="Select">
                                            <mat-option value="0">Select</mat-option>
                                            <mat-option value="India">India</mat-option>
                                            <mat-option value="United States">United States</mat-option>
                                            <mat-option value="Australia">Australia</mat-option>
                                            <mat-option value="Oman">Oman</mat-option>
                                            <mat-option value="Qatar">Qatar</mat-option>
                                        </mat-select>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-12"> 
                                    <div class="form-group">
                                        <label for="Subject">Subject</label>
                                        <input type="text" class="form-control" placeholder="Enter Subject">
                                    </div>
                                </div>							
                                <div class="col-md-12"> 
                                    <div class="form-group">
                                        <label for="Description">Description</label>
                                        <textarea class="form-control" rows="14" placeholder="Comments"></textarea>
                                    </div>
                                </div>
                            </div>		
                            <button type="submit" class="btn-primary">Submit Enquiry</button>
                        </div>
                    </div>					
                </form>
            </div>
            <div class="col-lg-6">
                <h3>Contact Details</h3>
                <div class="row">
                    <div class="col-lg-12 d-flex">
                        <div class="flex-fill">
                            <div class="contact-info-details d-flex align-items-center">
                                <span><img src="assets/img/icons/phone.svg" alt="Image"></span>
                                <div>														
                                    <h4>Call Us At</h4>
                                    <a href="tel:+16398098393">+1 63980 98393</a>,
                                    <a href="tel:+16398098393">+1 63980 98393</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 d-flex">
                        <div class="flex-fill">
                            <div class="contact-info-details d-flex align-items-center">
                                <span><img src="assets/img/icons/mail.svg" alt="Image"></span>
                                <div>														
                                    <h4>Email Us</h4>
                                    <a href="mailto:info&#64;example.com">info&#64;example.com</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 d-flex">
                        <div class="flex-fill">
                            <div class="contact-info-details d-flex align-items-center">
                                <span><img src="assets/img/icons/map-pin.svg" alt="Image"></span>
                                <div>														
                                    <h4>Location</h4>
                                    <p>Jl. Surabaya Jaya, No.10, Surabaya United States</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="map-location">
                    <h3>Find Us On</h3>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2967.8862835683544!2d-73.98256668525309!3d41.93829486962529!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89dd0ee3286615b7%3A0x42bfa96cc2ce4381!2s132%20Kingston%20St%2C%20Kingston%2C%20NY%2012401%2C%20USA!5e0!3m2!1sen!2sin!4v1670922579281!5m2!1sen!2sin" height="359"></iframe>
                </div>
                
            </div>
        </div>
    </div>
</section>
<!-- /Contact Info Details -->
