// angular/src/app/feature-module/listing/rent-property/rent-property-grid/rent-property-grid.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../../shared/routes/routes';

@Component({
  selector: 'app-rent-property-grid',
  templateUrl: './rent-property-grid.component.html',
  styleUrl: './rent-property-grid.component.scss',
})
export class RentPropertyGridComponent {
  isSelectAdded: boolean[] = [true];
  public isFavourite: boolean[] = Array(10).fill(true);
  public routes = routes;
  toggleSelect(index: number) {
    this.isSelectAdded[index] = !this.isSelectAdded[index];
  }
  toggleFavourite(index: number) {
    if (this.isFavourite[index] !== undefined) {
      this.isFavourite[index] = !this.isFavourite[index];
    }
  }
}

<!-- Breadcrumb -->
<div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Rent Property Grid without Sidebar</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink] = "routes.home">Home </a></li>
                    <li>Rent Property Grid without Sidebar</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" alt="Line Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->

<!-- Feature Property For Rent -->
<div class="listing-section">
    <div class="container">

        <!-- Sort Result -->
        <div class="showing-result-head">
            <div class="row align-items-center">
                <div class="col-lg-3">
                    <div class="result-show">
                        <h5>Showing result <span>06</span> of <span>125</span></h5>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="sort-result">
                        <div class="sort-by grid-head">
                            <div>
                                <p>Sort By</p>
                            </div>
                            <div class="review-form">
                                <mat-select class="custom-mat-select" placeholder="Default">
                                    <mat-option value="0">Default</mat-option>
                                    <mat-option value="1">A-Z</mat-option>
                                </mat-select>
                            </div>
                        </div>
                        <div class="price-range grid-head">
                            <div>
                                <p>Price Range</p>
                            </div>
                            <div class="review-form">
                                <mat-select class="custom-mat-select" placeholder="Low to High">
                                    <mat-option value="low">Low to High</mat-option>
                                    <mat-option value="high">High to Low</mat-option>
                                </mat-select>
                            </div>
                        </div>
                        <div class="grid-list-view">
                            <ul>
                                <li><a [routerLink] = "routes.rentPropertyGrid" class="active"><i class="bx bx-grid"></i></a></li>
                                <li><a [routerLink] = "routes.rentPropertyList"><i class="bx bx-list-ul"></i></a></li>
                                <li><a [routerLink] = "routes.rentGridMap"><i class="bx bxs-map"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Sort Result -->

        <div class="feature-property-sec for-rent for-rent p-0 bg-transparent">
            <div class="row">

                <!-- Rent grid -->
                <div class="col-lg-4 col-md-6">
                    <div class="product-custom">
                        <div class="profile-widget">
                            <div class="doc-img">
                                <a [routerLink] = "routes.rentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/product/product-6.jpg">
                                </a>
                                <div class="product-amount">
                                    <h5><span>$2,200 </span> / Night</h5>
                                </div>
                                <div class="featured">
                                    <span>Featured</span>
                                </div>
                                <div class="new-featured">
                                    <span>New</span> 
                                </div>
                                <a href="javascript:void(0)" (click)="toggleSelect(1)">
                                    <div class="favourite"
                                        [ngClass]="{ selected: isSelectAdded[1] }">
                                        <span><i class="fa-regular fa-heart"></i></span>
                                    </div>
                                </a>
                            </div>
                            <div class="pro-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <span class="rating-review">Excellent</span>
                                </div>
                                <h3 class="title">
                                    <a [routerLink] = "routes.rentDetails">Beautiful Condo Room</a> 
                                </h3>
                                <p><i class="feather icon-map-pin"></i> 318-S Oakley Blvd, Chicago, IL 60612, USA</p>
                                <ul class="d-flex details">
                                    <li>
                                        <img src="assets/img/icons/bed-icon.svg" alt="bed-icon" >
                                        4 Beds
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/bath-icon.svg" alt="bath-icon">
                                        4 Baths
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/building-icon.svg" alt="building-icon">
                                        35000 Sqft
                                    </li>
                                </ul>
                                <ul class="property-category d-flex justify-content-between align-items-center">
                                    <li class="user-info">
                                       <a [routerLink] = "routes.agentGrid"><img src="assets/img/profiles/avatar-01.jpg" class="img-fluid avatar" alt="User"></a>
                                        <div class="user-name">
                                            <a [routerLink] = "routes.agentGrid">Marc Silva</a>
                                            <p>Newyork</p>
                                        </div>													
                                    </li>
                                    <li>
                                        <a [routerLink] = "routes.rentDetails" class="btn-primary">Book Now</a>
                                    </li>
                                </ul>
                            </div>
                        </div>		
                    </div>
                </div>
                <!-- /Rent grid -->

                <!-- Rent grid -->
                <div class="col-lg-4 col-md-6">
                    <div class="product-custom">
                        <div class="profile-widget">
                            <div class="doc-img">
                                <a [routerLink] = "routes.rentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/product/product-7.jpg">
                                </a>
                                <div class="product-amount">
                                    <h5><span>$1,400 </span> / Night</h5>
                                </div>
                                <div class="featured">
                                    <span>Featured</span>
                                </div>
                                <a href="javascript:void(0)" (click)="toggleFavourite(1)">
                                    <div class="favourite" [ngClass]="{'selected': isFavourite[1]}">
                                        <i class="fa-regular fa-heart"></i>
                                    </div>
                                </a>
                            </div>
                            <div class="pro-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <span class="rating-review">Excellent</span>
                                </div>
                                <h3 class="title">
                                    <a [routerLink] = "routes.rentDetails">Grand Mahaka</a> 
                                </h3>
                                <p><i class="feather icon-map-pin"></i> 470 Park Ave S, New York, NY 10016</p>
                                <ul class="d-flex details">
                                    <li>
                                        <img src="assets/img/icons/bed-icon.svg" alt="bed-icon" >
                                        2 Beds
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/bath-icon.svg" alt="bath-icon">
                                        1 Baths
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/building-icon.svg" alt="building-icon">
                                        5000 Sqft
                                    </li>
                                </ul>
                                <ul class="property-category d-flex justify-content-between align-items-center">
                                    <li class="user-info">
                                        <a [routerLink] = "routes.agentGrid"><img src="assets/img/profiles/avatar-02.jpg" class="img-fluid avatar" alt="User"></a>
                                        <div class="user-name">
                                            <a [routerLink] = "routes.agentGrid">Karen Maria</a>
                                            <p>South Dokata</p>
                                        </div>													
                                    </li>
                                    <li>
                                        <a [routerLink] = "routes.rentDetails" class="btn-primary">Book Now</a>
                                    </li>
                                </ul>
                            </div>
                        </div>		
                    </div>
                </div>
                <!-- /Rent grid -->

                <!-- Rent grid -->
                <div class="col-lg-4 col-md-6">
                    <div class="product-custom">
                        <div class="profile-widget">
                            <div class="doc-img">
                                <a [routerLink] = "routes.rentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/product/product-8.jpg">
                                </a>
                                <div class="product-amount">
                                    <h5><span>$1,500 </span> / Night</h5>
                                </div>
                                <div class="featured">
                                    <span>Featured</span>
                                </div>
                                <a href="javascript:void(0)" (click)="toggleSelect(3)">
                                    <div class="favourite"
                                        [ngClass]="{ selected: isSelectAdded[3] }">
                                        <span><i class="fa-regular fa-heart"></i></span>
                                    </div>
                                </a>
                            </div>
                            <div class="pro-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <span class="rating-review">Excellent</span>
                                </div>
                                <h3 class="title">
                                    <a [routerLink] = "routes.rentDetails">Royal Apartment</a> 
                                </h3>
                                <p><i class="feather icon-map-pin"></i> 82-25 Parsons Blvd, Jamaica, NY 11432, USA</p>
                                <ul class="d-flex details">
                                    <li>
                                        <img src="assets/img/icons/bed-icon.svg" alt="bed-icon" >
                                        3 Beds
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/bath-icon.svg" alt="bath-icon">
                                        3 Baths
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/building-icon.svg" alt="building-icon">
                                        12000 Sqft
                                    </li>
                                </ul>
                                <ul class="property-category d-flex justify-content-between align-items-center">
                                    <li class="user-info">
                                        <a [routerLink] = "routes.agentGrid"><img src="assets/img/profiles/avatar-03.jpg" class="img-fluid avatar" alt="User"></a>
                                        <div class="user-name">
                                            <a [routerLink] = "routes.agentGrid">Scott Gwin</a>
                                            <p>Minipoliies</p>
                                        </div>													
                                    </li>
                                    <li>
                                        <a [routerLink] = "routes.rentDetails" class="btn-primary">Book Now</a>
                                    </li>
                                </ul>
                            </div>
                        </div>		
                    </div>
                </div>
                <!-- /Rent grid -->

                <!-- Rent grid -->
                <div class="col-lg-4 col-md-6">
                    <div class="product-custom">
                        <div class="profile-widget">
                            <div class="doc-img">
                                <a [routerLink] = "routes.rentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/product/product-9.jpg">
                                </a>
                                <div class="product-amount">
                                    <h5><span>$3,500 </span> / Night</h5>
                                </div>
                                <div class="featured">
                                    <span>Featured</span>
                                </div>
                                <a href="javascript:void(0)" (click)="toggleSelect(4)">
                                    <div class="favourite"
                                        [ngClass]="{ selected: isSelectAdded[4] }">
                                        <span><i class="fa-regular fa-heart"></i></span>
                                    </div>
                                </a>
                            </div>
                            <div class="pro-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star"></i>
                                    </span>
                                    <span class="rating-review">Excellent</span>
                                </div>
                                <h3 class="title">
                                    <a [routerLink] = "routes.rentDetails" tabindex="-1">Lunaria Residence</a> 
                                </h3>
                                <p><i class="feather icon-map-pin"></i> 518-520 8th Ave, New York, NY 10018, USA</p>
                                <ul class="d-flex details">
                                    <li>
                                        <img src="assets/img/icons/bed-icon.svg" alt="bed-icon" >
                                        4 Beds
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/bath-icon.svg" alt="bath-icon">
                                        2 Baths
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/building-icon.svg" alt="building-icon">
                                        31000 Sqft
                                    </li>
                                </ul>
                                <ul class="property-category d-flex justify-content-between align-items-center">
                                    <li class="user-info">
                                        <a [routerLink] = "routes.agentGrid"><img src="assets/img/profiles/avatar-04.jpg" class="img-fluid avatar" alt="User"></a>
                                        <div class="user-name">
                                            <a [routerLink] = "routes.agentGrid">Burdette</a>
                                            <p>Cambridge</p>
                                        </div>													
                                    </li>
                                    <li>
                                        <a [routerLink] = "routes.rentDetails" class="btn-primary">Book Now</a>
                                    </li>
                                </ul>
                            </div>
                        </div>		
                    </div>
                </div>
                <!-- /Rent grid -->

                <!-- Rent grid -->
                <div class="col-lg-4 col-md-6">
                    <div class="product-custom">
                        <div class="profile-widget">
                            <div class="doc-img">
                                <a [routerLink] = "routes.rentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/product/product-10.jpg">
                                </a>
                                <div class="product-amount">
                                    <h5><span>$4,500 </span> / Night</h5>
                                </div>
                                <div class="featured">
                                    <span>Featured</span>
                                </div>
                                <a href="javascript:void(0)" (click)="toggleFavourite(2)">
                                    <div class="favourite" [ngClass]="{'selected': isFavourite[2]}">
                                        <i class="fa-regular fa-heart"></i>
                                    </div>
                                </a>
                            </div>
                            <div class="pro-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <span class="rating-review">Excellent</span>
                                </div>
                                <h3 class="title">
                                    <a [routerLink] = "routes.rentDetails">Grand Villa house</a> 
                                </h3>
                                <p><i class="feather icon-map-pin"></i> 470 Park Ave S, New York, NY 10016</p>
                                <ul class="d-flex details">
                                    <li>
                                        <img src="assets/img/icons/bed-icon.svg" alt="bed-icon" >
                                        4 Beds
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/bath-icon.svg" alt="bath-icon">
                                        2 Baths
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/building-icon.svg" alt="building-icon">
                                        11000 Sqft
                                    </li>
                                </ul>
                                <ul class="property-category d-flex justify-content-between align-items-center">
                                    <li class="user-info">
                                        <a [routerLink] = "routes.agentGrid"><img src="assets/img/profiles/avatar-05.jpg" class="img-fluid avatar" alt="User"></a>
                                        <div class="user-name">
                                            <a [routerLink] = "routes.agentGrid">Kell Robinson</a>
                                            <p>USA</p>
                                        </div>													
                                    </li>
                                    <li>
                                        <a [routerLink] = "routes.rentDetails" class="btn-primary">Book Now</a>
                                    </li>
                                </ul>
                            </div>
                        </div>		
                    </div>
                </div>
                <!-- /Rent grid -->

                <!-- Rent grid -->
                <div class="col-lg-4 col-md-6">
                    <div class="product-custom">
                        <div class="profile-widget">
                            <div class="doc-img">
                                <a [routerLink] = "routes.rentDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/product/product-11.jpg">
                                </a>
                                <div class="product-amount">
                                    <h5><span>$2,400 </span> / Night</h5>
                                </div>
                                <div class="featured">
                                    <span>Featured</span>
                                </div>
                                <a href="javascript:void(0)" (click)="toggleSelect(6)">
                                    <div class="favourite"
                                        [ngClass]="{ selected: isSelectAdded[6] }">
                                        <span><i class="fa-regular fa-heart"></i></span>
                                    </div>
                                </a>
                            </div>
                            <div class="pro-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <span class="rating-review">Excellent</span>
                                </div>
                                <h3 class="title">
                                    <a [routerLink] = "routes.rentDetails">Stephen Alexander Homes</a> 
                                </h3>
                                <p><i class="feather icon-map-pin"></i> 122 N Morgan St, Chicago, IL 60607, USA</p>
                                <ul class="d-flex details">
                                    <li>
                                        <img src="assets/img/icons/bed-icon.svg" alt="bed-icon" >
                                        1 Beds
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/bath-icon.svg" alt="bath-icon">
                                        1 Baths
                                    </li>
                                    <li>
                                        <img src="assets/img/icons/building-icon.svg" alt="building-icon">
                                        7000 Sqft
                                    </li>
                                </ul>
                                <ul class="property-category d-flex justify-content-between align-items-center">
                                    <li class="user-info">
                                        <a [routerLink] = "routes.agentGrid"><img src="assets/img/profiles/avatar-07.jpg" class="img-fluid avatar" alt="User"></a>
                                        <div class="user-name">
                                            <a [routerLink] = "routes.agentGrid">Pittman</a>
                                            <p>Cambridge</p>
                                        </div>													
                                    </li>
                                    <li>
                                        <a [routerLink] = "routes.rentDetails" class="btn-primary">Book Now</a>
                                    </li>
                                </ul>
                            </div>
                        </div>		
                    </div>
                </div>
                <!-- /Rent grid -->

            </div>
        </div>
    </div>
</div>
<!-- /Feature Property For Rent -->

// react/src/feature-module/listing/rentProperty/rentPropertyGrid/index.tsx
import React, { useState } from 'react'
import BreadCrumb from '../../../../core/common/breadCrumb'
import ImageWithBasePath from '../../../../core/img'
import { Link } from 'react-router-dom'
import { customStyles, lowToHigh, sortBy } from '../../../../core/common/select'
import Select from 'react-select';
import { MapPin } from 'react-feather'
import { all_routes } from '../../../router/all_routes'
const RentPropertyGrid = () => {
  const routes = all_routes

  const [isClassAdded, setIsClassAdded] = useState([false, true, false, false, true, true, false, true, true]); // Set the second button as initially selected

  const toggleClass = (index: any) => {
    const updatedClasses = [...isClassAdded];
    updatedClasses[index] = !updatedClasses[index];
    setIsClassAdded(updatedClasses);
  }; 
  return (
    <>
    {/* Breadcrumb */}
    <BreadCrumb title="Rent Property Grid without Sidebar" pageTitle="Home" />
    {/* Breadcrumb */}
    {/* Feature Property For Rent */}
    <div className="listing-section">
      <div className="container">
        {/* Sort Result */}
        <div className="showing-result-head">
          <div className="row align-items-center">
            <div className="col-lg-3">
              <div className="result-show">
                <h5>
                  Showing result <span>06</span> of <span>125</span>
                </h5>
              </div>
            </div>
            <div className="col-lg-9">
              <div className="sort-result">
                <div className="sort-by grid-head">
                  <div>
                    <p>Sort By</p>
                  </div>
                  <div className="review-form">
                  <Select options={sortBy} defaultValue={sortBy[0]} className="select" styles={customStyles} />

                  </div>
                </div>
                <div className="price-range grid-head">
                  <div>
                    <p>Price Range</p>
                  </div>
                  <div className="review-form">
                    <Select options={lowToHigh} defaultValue={lowToHigh[0]} className="select" styles={customStyles} />
                  </div>
                </div>
                <div className="grid-list-view">
                  <ul>
                    <li>
                      <Link to={routes.rentGrid} className="active">
                        <i className="bx bx-grid" />
                      </Link>
                    </li>
                    <li>
                      <Link to={routes.rentPropertyList}>
                        <i className="bx bx-list-ul" />
                      </Link>
                    </li>
                    <li>
                      <Link to={routes.rentGridMap}>
                        <i className="bx bxs-map" />
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* /Sort Result */}
        <div className="feature-property-sec for-rent for-rent p-0 bg-transparent">
          <div className="row">
            {/* Rent grid */}
            <div className="col-lg-4 col-md-6">
              <div className="product-custom">
                <div className="profile-widget">
                  <div className="doc-img">
                    <Link to={routes.rentDetails} className="property-img">
                      <ImageWithBasePath
                        className="img-fluid"
                       alt='img'
                        src="assets/img/product/product-6.jpg"
                      />
                    </Link>
                    <div className="product-amount">
                      <h5>
                        <span>$2,200 </span> / Night
                      </h5>
                    </div>
                    <div className="featured">
                      <span>Featured</span>
                    </div>
                    <div className="new-featured">
                      <span>New</span>
                    </div>
                    <Link to="#"onClick={() => toggleClass(0)}>
                                <div className={`favourite ${isClassAdded[0] ? 'favourite selected' : ''}`}>
                                  <span>
                                    <i className="fa-regular fa-heart" />
                                  </span>
                                </div>
                              </Link>
                  </div>
                  <div className="pro-content">
                    <div className="rating">
                      <span className="rating-count">
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                      </span>
                      <span className="rating-review">Excellent</span>
                    </div>
                    <h3 className="title">
                      <Link to={routes.rentDetails}>Beautiful Condo Room</Link>
                    </h3>
                    <p>
                      <MapPin size={15} className='me-1'/> 318-S Oakley Blvd,
                      Chicago, IL 60612, USA
                    </p>
                    <ul className="d-flex details">
                      <li>
                        <ImageWithBasePath src="assets/img/icons/bed-icon.svg" alt="bed-icon" />
                        4 Beds
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/bath-icon.svg"
                          alt="bath-icon"
                        />
                        4 Baths
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/building-icon.svg"
                          alt="building-icon"
                        />
                        35000 Sqft
                      </li>
                    </ul>
                    <ul className="property-category d-flex justify-content-between align-items-center">
                      <li className="user-info">
                        <Link to={routes.agentGrid}>
                          <ImageWithBasePath
                            src="assets/img/profiles/avatar-01.jpg"
                            className="img-fluid avatar"
                            alt="User"
                          />
                        </Link>
                        <div className="user-name">
                          <Link to={routes.agentGrid}>Marc Silva</Link>
                          <p>Newyork</p>
                        </div>
                      </li>
                      <li>
                        <Link to={routes.rentDetails} className="btn-primary">
                          Book Now
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            {/* /Rent grid */}
            {/* Rent grid */}
            <div className="col-lg-4 col-md-6">
              <div className="product-custom">
                <div className="profile-widget">
                  <div className="doc-img">
                    <Link to={routes.rentDetails} className="property-img">
                      <ImageWithBasePath
                        className="img-fluid"
                       alt='img'
                        src="assets/img/product/product-7.jpg"
                      />
                    </Link>
                    <div className="product-amount">
                      <h5>
                        <span>$1,400 </span> / Night
                      </h5>
                    </div>
                    <div className="featured">
                      <span>Featured</span>
                    </div>
                    <Link to="#"onClick={() => toggleClass(1)}>
                                <div className={`favourite ${isClassAdded[1] ? 'favourite selected' : ''}`}>
                                  <span>
                                    <i className="fa-regular fa-heart" />
                                  </span>
                                </div>
                              </Link>
                  </div>
                  <div className="pro-content">
                    <div className="rating">
                      <span className="rating-count">
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                      </span>
                      <span className="rating-review">Excellent</span>
                    </div>
                    <h3 className="title">
                      <Link to={routes.rentDetails}>Grand Mahaka</Link>
                    </h3>
                    <p>
                      <MapPin size={15} className='me-1'/> 470 Park Ave S, New York,
                      NY 10016
                    </p>
                    <ul className="d-flex details">
                      <li>
                        <ImageWithBasePath src="assets/img/icons/bed-icon.svg" alt="bed-icon" />
                        2 Beds
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/bath-icon.svg"
                          alt="bath-icon"
                        />
                        1 Baths
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/building-icon.svg"
                          alt="building-icon"
                        />
                        5000 Sqft
                      </li>
                    </ul>
                    <ul className="property-category d-flex justify-content-between align-items-center">
                      <li className="user-info">
                        <Link to={routes.agentGrid}>
                          <ImageWithBasePath
                            src="assets/img/profiles/avatar-02.jpg"
                            className="img-fluid avatar"
                            alt="User"
                          />
                        </Link>
                        <div className="user-name">
                          <Link to={routes.agentGrid}>Karen Maria</Link>
                          <p>South Dokata</p>
                        </div>
                      </li>
                      <li>
                        <Link to={routes.rentDetails} className="btn-primary">
                          Book Now
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            {/* /Rent grid */}
            {/* Rent grid */}
            <div className="col-lg-4 col-md-6">
              <div className="product-custom">
                <div className="profile-widget">
                  <div className="doc-img">
                    <Link to={routes.rentDetails} className="property-img">
                      <ImageWithBasePath
                        className="img-fluid"
                       alt='img'
                        src="assets/img/product/product-8.jpg"
                      />
                    </Link>
                    <div className="product-amount">
                      <h5>
                        <span>$1,500 </span> / Night
                      </h5>
                    </div>
                    <div className="featured">
                      <span>Featured</span>
                    </div>
                    <Link to="#"onClick={() => toggleClass(2)}>
                                <div className={`favourite ${isClassAdded[2] ? 'favourite selected' : ''}`}>
                                  <span>
                                    <i className="fa-regular fa-heart" />
                                  </span>
                                </div>
                              </Link>
                  </div>
                  <div className="pro-content">
                    <div className="rating">
                      <span className="rating-count">
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                      </span>
                      <span className="rating-review">Excellent</span>
                    </div>
                    <h3 className="title">
                      <Link to={routes.rentDetails}>Royal Apartment</Link>
                    </h3>
                    <p>
                      <MapPin size={15} className='me-1'/> 82-25 Parsons Blvd,
                      Jamaica, NY 11432, USA
                    </p>
                    <ul className="d-flex details">
                      <li>
                        <ImageWithBasePath src="assets/img/icons/bed-icon.svg" alt="bed-icon" />
                        3 Beds
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/bath-icon.svg"
                          alt="bath-icon"
                        />
                        3 Baths
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/building-icon.svg"
                          alt="building-icon"
                        />
                        12000 Sqft
                      </li>
                    </ul>
                    <ul className="property-category d-flex justify-content-between align-items-center">
                      <li className="user-info">
                        <Link to={routes.agentGrid}>
                          <ImageWithBasePath
                            src="assets/img/profiles/avatar-03.jpg"
                            className="img-fluid avatar"
                            alt="User"
                          />
                        </Link>
                        <div className="user-name">
                          <Link to={routes.agentGrid}>Scott Gwin</Link>
                          <p>Minipoliies</p>
                        </div>
                      </li>
                      <li>
                        <Link to={routes.rentDetails} className="btn-primary">
                          Book Now
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            {/* /Rent grid */}
            {/* Rent grid */}
            <div className="col-lg-4 col-md-6">
              <div className="product-custom">
                <div className="profile-widget">
                  <div className="doc-img">
                    <Link to={routes.rentDetails} className="property-img">
                      <ImageWithBasePath
                        className="img-fluid"
                       alt='img'
                        src="assets/img/product/product-9.jpg"
                      />
                    </Link>
                    <div className="product-amount">
                      <h5>
                        <span>$3,500 </span> / Night
                      </h5>
                    </div>
                    <div className="featured">
                      <span>Featured</span>
                    </div>
                    <Link to="#"onClick={() => toggleClass(3)}>
                                <div className={`favourite ${isClassAdded[3] ? 'favourite selected' : ''}`}>
                                  <span>
                                    <i className="fa-regular fa-heart" />
                                  </span>
                                </div>
                              </Link>
                  </div>
                  <div className="pro-content">
                    <div className="rating">
                      <span className="rating-count">
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star" />
                      </span>
                      <span className="rating-review">Excellent</span>
                    </div>
                    <h3 className="title">
                      <Link to={routes.rentDetails} tabIndex={-1}>
                        Lunaria Residence
                      </Link>
                    </h3>
                    <p>
                      <MapPin size={15} className='me-1'/> 518-520 8th Ave, New York,
                      NY 10018, USA
                    </p>
                    <ul className="d-flex details">
                      <li>
                        <ImageWithBasePath src="assets/img/icons/bed-icon.svg" alt="bed-icon" />
                        4 Beds
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/bath-icon.svg"
                          alt="bath-icon"
                        />
                        2 Baths
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/building-icon.svg"
                          alt="building-icon"
                        />
                        31000 Sqft
                      </li>
                    </ul>
                    <ul className="property-category d-flex justify-content-between align-items-center">
                      <li className="user-info">
                        <Link to={routes.agentGrid}>
                          <ImageWithBasePath
                            src="assets/img/profiles/avatar-04.jpg"
                            className="img-fluid avatar"
                            alt="User"
                          />
                        </Link>
                        <div className="user-name">
                          <Link to={routes.agentGrid}>Burdette</Link>
                          <p>Cambridge</p>
                        </div>
                      </li>
                      <li>
                        <Link to={routes.rentDetails} className="btn-primary">
                          Book Now
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            {/* /Rent grid */}
            {/* Rent grid */}
            <div className="col-lg-4 col-md-6">
              <div className="product-custom">
                <div className="profile-widget">
                  <div className="doc-img">
                    <Link to={routes.rentDetails} className="property-img">
                      <ImageWithBasePath
                        className="img-fluid"
                       alt='img'
                        src="assets/img/product/product-10.jpg"
                      />
                    </Link>
                    <div className="product-amount">
                      <h5>
                        <span>$4,500 </span> / Night
                      </h5>
                    </div>
                    <div className="featured">
                      <span>Featured</span>
                    </div>
                    <Link to="#"onClick={() => toggleClass(4)}>
                                <div className={`favourite ${isClassAdded[4] ? 'favourite selected' : ''}`}>
                                  <span>
                                    <i className="fa-regular fa-heart" />
                                  </span>
                                </div>
                              </Link>
                  </div>
                  <div className="pro-content">
                    <div className="rating">
                      <span className="rating-count">
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                      </span>
                      <span className="rating-review">Excellent</span>
                    </div>
                    <h3 className="title">
                      <Link to={routes.rentDetails}>Grand Villa house</Link>
                    </h3>
                    <p>
                      <MapPin size={15} className='me-1'/> 470 Park Ave S, New York,
                      NY 10016
                    </p>
                    <ul className="d-flex details">
                      <li>
                        <ImageWithBasePath src="assets/img/icons/bed-icon.svg" alt="bed-icon" />
                        4 Beds
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/bath-icon.svg"
                          alt="bath-icon"
                        />
                        2 Baths
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/building-icon.svg"
                          alt="building-icon"
                        />
                        11000 Sqft
                      </li>
                    </ul>
                    <ul className="property-category d-flex justify-content-between align-items-center">
                      <li className="user-info">
                        <Link to={routes.agentGrid}>
                          <ImageWithBasePath
                            src="assets/img/profiles/avatar-05.jpg"
                            className="img-fluid avatar"
                            alt="User"
                          />
                        </Link>
                        <div className="user-name">
                          <Link to={routes.agentGrid}>Kell Robinson</Link>
                          <p>USA</p>
                        </div>
                      </li>
                      <li>
                        <Link to={routes.rentDetails} className="btn-primary">
                          Book Now
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            {/* /Rent grid */}
            {/* Rent grid */}
            <div className="col-lg-4 col-md-6">
              <div className="product-custom">
                <div className="profile-widget">
                  <div className="doc-img">
                    <Link to={routes.rentDetails} className="property-img">
                      <ImageWithBasePath
                        className="img-fluid"
                       alt='img'
                        src="assets/img/product/product-11.jpg"
                      />
                    </Link>
                    <div className="product-amount">
                      <h5>
                        <span>$2,400 </span> / Night
                      </h5>
                    </div>
                    <div className="featured">
                      <span>Featured</span>
                    </div>
                    <Link to="#"onClick={() => toggleClass(5)}>
                                <div className={`favourite ${isClassAdded[5] ? 'favourite selected' : ''}`}>
                                  <span>
                                    <i className="fa-regular fa-heart" />
                                  </span>
                                </div>
                              </Link>
                  </div>
                  <div className="pro-content">
                    <div className="rating">
                      <span className="rating-count">
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                        <i className="fa-solid fa-star checked" />
                      </span>
                      <span className="rating-review">Excellent</span>
                    </div>
                    <h3 className="title">
                      <Link to={routes.rentDetails}>Stephen Alexander Homes</Link>
                    </h3>
                    <p>
                      <MapPin size={15} className='me-1'/> 122 N Morgan St, Chicago,
                      IL 60607, USA
                    </p>
                    <ul className="d-flex details">
                      <li>
                        <ImageWithBasePath src="assets/img/icons/bed-icon.svg" alt="bed-icon" />
                        1 Beds
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/bath-icon.svg"
                          alt="bath-icon"
                        />
                        1 Baths
                      </li>
                      <li>
                        <ImageWithBasePath
                          src="assets/img/icons/building-icon.svg"
                          alt="building-icon"
                        />
                        7000 Sqft
                      </li>
                    </ul>
                    <ul className="property-category d-flex justify-content-between align-items-center">
                      <li className="user-info">
                        <Link to={routes.agentGrid}>
                          <ImageWithBasePath
                            src="assets/img/profiles/avatar-07.jpg"
                            className="img-fluid avatar"
                            alt="User"
                          />
                        </Link>
                        <div className="user-name">
                          <Link to={routes.agentGrid}>Pittman</Link>
                          <p>Cambridge</p>
                        </div>
                      </li>
                      <li>
                        <Link to={routes.rentDetails} className="btn-primary">
                          Book Now
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            {/* /Rent grid */}
          </div>
        </div>
      </div>
    </div>
    {/* /Feature Property For Rent */}
  </>
  
  )
}

export default RentPropertyGrid
