// angular/src/app/feature-module/common/header/header.component.ts
import { Component, HostListener, OnDestroy, OnInit } from '@angular/core';
import { CommonService } from '../../../shared/common/common.service';
import { DataService } from '../../../shared/data/data.service';
import { SidebarService } from '../../../shared/sidebar/sidebar.service';
import { routes } from '../../../shared/routes/routes';
import { NavigationStart, Router } from '@angular/router';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss',
})
export class HeaderComponent implements OnInit, OnDestroy {
  public routes = routes;
  base = '';
  page = '';
  last = '';
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  header: any = [];

  constructor(
    private common: CommonService,
    private data: DataService,
    private sidebar: SidebarService,
    private router: Router
  ) {
    this.common.base.subscribe((res: string) => {
      this.base = res;
    });
    this.common.page.subscribe((res: string) => {
      this.page = res;
    });
    this.common.last.subscribe((res: string) => {
      this.last = res;
    });
    console.log("base", this.base);
    console.log("page", this.page);
    console.log("last", this.last);

    this.header = this.data.header;
  }
  public toggleSidebar(): void {
    this.sidebar.openSidebar();
  }
  public hideSidebar(): void {
    this.sidebar.closeSidebar();
  }
  @HostListener('window:scroll', [])
  onWindowScroll() {
    const scroll =
      window.pageYOffset ||
      document.documentElement.scrollTop ||
      document.body.scrollTop ||
      0;
    const headerOne = document.querySelector('.header-fix');
    if (headerOne && scroll > 35) {
      headerOne.classList.add('nav-fixed');
    } else if (headerOne) {
      headerOne.classList.remove('nav-fixed');
    }
  }
  public searchPopup = false;
  private routerSubscription: Subscription | undefined;


  ngOnInit() {
    this.routerSubscription = this.router.events.subscribe(event => {
      if (event instanceof NavigationStart) {
        this.searchPopup = false; 
      }
    });
  }

  ngOnDestroy() {
    if (this.routerSubscription) {
      this.routerSubscription.unsubscribe(); 
    }
  }

  showSearchPopup() {
    this.searchPopup = !this.searchPopup;
  }
  public navigate(){
    this.router.navigate([routes.rentPropertyGrid])
  }
}

<!-- Header -->
<header class="header header-fix">
  <div class="header-top" *ngIf="base === 'home'">
    <div class="template-ad">
      <img src="assets/img/icons/badge-icon.svg" alt="icon">
      <h5>No 1, Realestate Website to Buy / Sell Your Place <span>First Listing Free!!!</span></h5>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg header-nav">
    <div class="navbar-header">
      <a id="mobile_btn" href="javascript:void(0);" (click)="toggleSidebar()">
        <span class="bar-icon">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </a>
      <a [routerLink]="routes.home" class="navbar-brand logo">
        <img src="assets/img/logo.svg" class="img-fluid" alt="Logo">
      </a>
    </div>
    <div class="main-menu-wrapper">
      <div class="menu-header">
        <a [routerLink]="routes.home" class="menu-logo">
          <img src="assets/img/logo.svg" class="img-fluid" alt="Logo">
        </a>

        <a id="menu_close" class="menu-close" href="javascript:void(0);" (click)="hideSidebar()">
          <i class="fas fa-times"></i>
        </a>
      </div>
      <ul class="main-nav">
        @for (mainMenus of header; track mainMenus) {
        @if (mainMenus.separateRoute === true) {
        <li routerLinkActive="active">
          <a [routerLink]="mainMenus.routes">{{ mainMenus.tittle }}</a>
        </li>
        }
        @if (mainMenus.separateRoute === false) {
        <li class="has-submenu" routerLinkActive="active">
          <a href="javascript:void(0);" (click)="mainMenus.showAsTab = !mainMenus.showAsTab">{{ mainMenus.tittle }} <i
              class="fas fa-chevron-down"></i></a>
          <ul class="submenu" [ngClass]="{
                        'd-block': mainMenus.showAsTab === true
                      }">
            @for (menu of mainMenus.menu; track menu) {
            @if (menu.hasSubRoute === false) {
            <li>
              <a [routerLink]="menu.routes" routerLinkActive="active">{{ menu.menuValue }}</a>
            </li>
            }
            @if (menu.hasSubRoute === true) {
            <li class="has-submenu" routerLinkActive="active">
              <a (click)="menu.showSubRoute = !menu.showSubRoute" [routerLink]="menu.routes">{{ menu.menuValue }}</a>
              <ul class="submenu" [ngClass]="{
                                'd-block': menu.showSubRoute === true
                              }">
                @for (subMenu of menu.subMenus; track subMenu) {
                <li>
                  <a routerLinkActive="active" [routerLink]="subMenu.routes">{{
                    subMenu.menuValue
                    }}</a>
                </li>
                }
              </ul>
            </li>
            }
            }
          </ul>
        </li>
        }
        }
        <li class="searchbar">
          <a href="javascript:void(0);" (click)="showSearchPopup()">
            <img src="assets/img/icons/search-icon.svg" alt="img">
          </a>
        </li>
      </ul>
    </div>
    <ul class="nav header-navbar-rht">
      <li class="new-property-btn">
        <a [routerLink]="routes.addNewProperty">
          <i class="bx bxs-plus-circle"></i> Add New Property
        </a>
      </li>
      <li>
        <a [routerLink]="routes.register" class="btn btn-primary"><i class="feather icon-user-plus"></i>Sign Up</a>
      </li>
      <li>
        <a [routerLink]="routes.login" class="btn sign-btn"><i class="feather icon-unlock"></i>Sign In</a>
      </li>
    </ul>
  </nav>
</header>
<!-- /Header -->
<!-- Search -->
<div class="search-popup js-search-popup " [ngClass]="{'visible': searchPopup === true}">
  <a href="javascript:void(0);" class="close-button" id="search-close" aria-label="Close search"
    (click)="showSearchPopup()">
    <i class="fa fa-close"></i>
  </a>
  <div class="popup-inner">
    <div class="inner-container">
      <form class="search-form" id="search-form">
        <h3>What Are You Looking for?</h3>
        <div class="search-form-box flex">
          <input type="text" class="search-input" placeholder="Type a  Keyword...." id="search-input"
            aria-label="Type to search" role="searchbox" autocomplete="off">
          <button type="button" class="search-icon" (click)="navigate()"><i class="bx bx-search"></i></button>
        </div>
        <h5>Popular Properties</h5>
        <ul>
          <li><a [routerLink]="routes.rentPropertyGrid">Beautiful Condo Room</a></li>
          <li><a [routerLink]="routes.rentPropertyGrid">Royal Apartment</a></li>
          <li><a [routerLink]="routes.rentPropertyGrid">Grand Villa House</a></li>
          <li><a [routerLink]="routes.rentPropertyGrid">Grand Mahaka</a></li>
          <li><a [routerLink]="routes.rentPropertyGrid">Lunaria Residence</a></li>
          <li><a [routerLink]="routes.rentPropertyGrid">Stephen Alexander Homes</a></li>
        </ul>
      </form>
    </div>
  </div>
</div>
<!-- /Search -->

// react/src/core/common/header/index.tsx
import React, { useEffect, useState } from "react";
import ImageWithBasePath from "../../img";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { header } from "../../json/headerData";
import { all_routes } from "../../../feature-module/router/all_routes";
import { Unlock, UserPlus } from "react-feather";

const Header = () => {
  const navigate = useNavigate();

  const [searchPopup, setSearchPopup] = useState(false);

  const showSearchPopup = () => {
    setSearchPopup(!searchPopup); // Toggle the searchPopup state
  };

  const handleNavigate = () => {
    // Navigate to the desired route
    navigate(routes.rentGridWithSidebar);
    // Hide the search popup
    setSearchPopup(false);
  };
  const routes = all_routes;
  const location = useLocation();
  const pagesActiveClassArray = [
    "/listing/buy-property-grid",
    // "/pages/aboutus",
    // "/authentication/register",
    // "/authentication/login",
    // "/authentication/forgot-password",
    // "/authentication/reset-password",
    // "/pages/booking-payment",
    // "/pages/booking-payment",
    // "/pages/invoice-details",
    // "/pages/error-404",
    // "/pages/error-500",
    // "/pages/pricing",
    // "/pages/faq",
    // "/pages/gallery",
    // "/pages/our-team",
    // "/pages/testimonial",
    // "/pages/terms-condition",
    // "/pages/privacy-policy",
    // "/pages/maintenance",
    // "/pages/coming-soon",
  ];
  const handlesidebarmobilemenu = () => {
    document.body.classList.toggle("slide-nav");
    document.getElementsByTagName("html")[0].classList.toggle("menu-opened");
    document
      .getElementsByClassName("sidebar-overlay")[0]
      .classList.toggle("opened");
  };
  const isHomePage =
    location.pathname === "/" || location.pathname === "/index";

  const [headerClass, setHeaderClass] = useState("header header-fix");
  useEffect(() => {
    const handleScroll = () => {
      const scrollPosition = window.scrollY;
      const scrollThreshold = 100;

      if (scrollPosition > scrollThreshold) {
        setHeaderClass("header header-fix nav-fixed");
      } else {
        setHeaderClass("header header-fix");
      }
    };
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []); // Empty dependency array to run this effect only once on component mount
  
  return (
    <div>
      <header className={headerClass} style={{ position: "sticky" }}>
        {/* Header content goes here */}
        {isHomePage && (
          <div className="header-top">
            <div className="template-ad">
              <ImageWithBasePath
                src="assets/img/icons/badge-icon.svg"
                alt="icon"
              />
              <h5>
                No 1, Real Estate Website to Buy / Sell Your Place{" "}
                <span>First Listing Free!!!</span>
              </h5>
            </div>
          </div>
        )}
        <div className="header header-trans">
          <nav className="navbar navbar-expand-lg header-nav">
            <div className="navbar-header">
              <Link id="mobile_btn" to="#" onClick={handlesidebarmobilemenu}>
                <span className="bar-icon">
                  <span />
                  <span />
                  <span />
                </span>
              </Link>
              <Link to={routes.home} className="navbar-brand logo">
                <ImageWithBasePath
                  src="assets/img/logo.svg"
                  className="img-fluid"
                  alt="Logo"
                />
              </Link>
            </div>
            <div className="main-menu-wrapper">
              <div className="menu-header">
                <Link to={routes.home} className="menu-logo">
                  <ImageWithBasePath
                    src="assets/img/logo.svg"
                    className="img-fluid"
                    alt="Logo"
                  />
                </Link>
                <Link id="menu_close" className="menu-close" to="#">
                  <i className="fas fa-times" />
                </Link>
              </div>
              <ul className="main-nav">
                {header.map((mainMenus, mainIndex) => {
                  return (
                    <React.Fragment key={mainIndex}>
                      {mainMenus.separateRoute ? (
                        <li
                          key={mainIndex}
                          className={
                            location.pathname.includes(
                              mainMenus.routes || ""
                            ) ||
                            (mainMenus.title === "" &&
                              pagesActiveClassArray?.map((name) =>
                                name.includes(location.pathname)
                              ))
                              ? "active"
                              : ""
                          }
                        >
                          {/* {checkActiceClass(mainMenus)} */}
                          {/* <Link to={mainMenus.routes}>{mainMenus.title}</Link> */}
                          <Link to={mainMenus.routes || routes.home}>
                            {mainMenus.title}
                          </Link>
                        </li>
                      ) : (
                        <li
                          className={`has-submenu ${
                            mainMenus?.menu
                              ?.map((item) => item?.routes)
                              .includes(location.pathname) ||
                            (location.pathname.startsWith("/listing/") &&
                              mainMenus.title === "Listing")
                              ? "active"
                              : ""
                          }`}
                        >
                          <Link to="#">
                            {mainMenus.title}{" "}
                            <i className="fas fa-chevron-down"></i>
                          </Link>
                          <ul
                            className={`submenu ${
                              mainMenus.showAsTab ? "d-block" : ""
                            }`}
                          >
                            {mainMenus.menu?.map((menu, menuIndex) => (
                              <li
                                key={menuIndex}
                                className={`${
                                  menu.hasSubRoute ? "has-submenu" : ""
                                } ${
                                  menu?.subMenus
                                    ?.map((item) => item?.routes)
                                    .includes(location.pathname)
                                    ? "active"
                                    : ""
                                }`}
                              >
                                {menu.hasSubRoute ? (
                                  <React.Fragment>
                                    <Link to="#">{menu.menuValue}</Link>
                                    <ul
                                      className={`submenu ${
                                        menu.showSubRoute ? "d-block" : ""
                                      }`}
                                    >
                                      {menu.subMenus?.map(
                                        (subMenu, subMenuIndex) => (
                                          <li
                                            key={subMenuIndex}
                                            className={
                                              location.pathname ===
                                              subMenu.routes
                                                ? "active"
                                                : ""
                                            }
                                          >
                                            <Link to={subMenu.routes}>
                                              {subMenu.menuValue}
                                            </Link>
                                          </li>
                                        )
                                      )}
                                    </ul>
                                  </React.Fragment>
                                ) : (
                                  <li
                                    className={
                                      location.pathname.includes(
                                        menu.routes || ""
                                      )
                                        ? "active"
                                        : ""
                                    }
                                  >
                                    <Link to={menu.routes ?? routes.home}>
                                      {menu.menuValue}
                                    </Link>
                                  </li>
                                )}
                              </li>
                            ))}
                          </ul>
                        </li>
                        
                      )}
                    </React.Fragment>
                  );
                })}
              </ul>
            </div>
            <div className="searchbar ms-3">
              <Link to="#" onClick={showSearchPopup}>
                <ImageWithBasePath
                  src="assets/img/icons/search-icon.svg"
                  alt="img"
                />
              </Link>
            </div>
            <ul className="nav header-navbar-rht">
              <li className="new-property-btn">
                <Link to={routes.addNewProperty}>
                  <i className="bx bxs-plus-circle" /> Add New Property
                </Link>
              </li>
              <li>
                <Link to={routes.register} className="btn btn-primary">
                  <UserPlus size={15} className="me-1" />
                  Sign Up
                </Link>
              </li>
              <li>
                <Link to={routes.login} className="btn sign-btn">
                  <Unlock size={15} className="me-1" />
                  Sign In
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </header>
      {/* /Header */}
      <>
        <div
          className={`search-popup js-search-popup ${
            searchPopup ? "visible" : ""
          }`}
        >
          <Link
            to="#"
            className="close-button"
            id="search-close"
            aria-label="Close search"
            onClick={showSearchPopup}
          >
            <i className="fa fa-close"></i>
          </Link>
          <div className="popup-inner">
            <div className="inner-container">
              <form className="search-form" id="search-form">
                <h3>What Are You Looking for?</h3>
                <div className="search-form-box flex">
                  <input
                    type="text"
                    className="search-input"
                    placeholder="Type a Keyword...."
                    id="search-input"
                    aria-label="Type to search"
                    role="searchbox"
                    autoComplete="off"
                  />
                  <button
                    type="button"
                    className="search-icon"
                    onClick={handleNavigate}
                  >
                    <i className="bx bx-search"></i>
                  </button>
                </div>
                <h5>Popular Properties</h5>
                <ul>
                  <li>
                    {/* Use Link component to navigate */}
                    <Link to={routes.rentGridWithSidebar} onClick={handleNavigate}>
                      Beautiful Condo Room
                    </Link>
                    </li>
                    <li>
                    <Link to={routes.rentGridWithSidebar} onClick={handleNavigate}>
                    Royal Apartment
                    </Link>
                    </li>
                    <li>
                    <Link to={routes.rentGridWithSidebar} onClick={handleNavigate}>
                    Grand Villa House
                    </Link>
                    </li>
                    <li>
                    <Link to={routes.rentGridWithSidebar} onClick={handleNavigate}>
                    Grand Mahaka
                    </Link>
                    </li>
                    <li>
                    <Link to={routes.rentGridWithSidebar} onClick={handleNavigate}>
                    Lunaria Residence
                    </Link>
                    </li>
                    <li>
                    <Link to={routes.rentGridWithSidebar} onClick={handleNavigate}>
                    Stephen Alexander Homes
                    </Link>
                    </li>
                  
                  {/* Add other list items */}
                </ul>
              </form>
            </div>
          </div>
        </div>
      </>
    </div>
  );
};

export default Header;
