// react/src/feature-module/pages/authentication/register.tsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import { all_routes } from "../../router/all_routes";

const Register = () => {
  const routes = all_routes;
  const [passwordType, setPasswordType] = useState("password");
  const [passwordInput, setPasswordInput] = useState("");
  const handlePasswordChange =(evnt: { target: { value: React.SetStateAction<string>; }; })=>{
    setPasswordInput(evnt.target.value);
}
  
 
  const togglePassword =()=>{
    if(passwordType==="password")
    {
     setPasswordType("text")
     return;
    }
    setPasswordType("password")
  }
  return (
    <div className="login-body">
      <div className="container">
        {/* Header */}
        <header className="log-header">
          <Link to={routes.home}>
            <img
              className="img-fluid logo-dark"
              src="assets/img/logo.svg"
              alt="Logo"
            />
         </Link>
        </header>
        {/* /Header */}
        <div className="login-wrapper">
          <div className="loginbox">
            <div className="login-auth">
              <div className="login-auth-wrap">
                <h1>
                  Signup! <span className="d-block"> New Account.</span>
                </h1>
                <form >
                  <div className="form-group">
                    <label className="form-label">
                      Name <span>*</span>
                    </label>
                    <input
                      type="text"
                      className="form-control"
                      placeholder="Enter Name"
                    />
                  </div>
                  <div className="form-group">
                    <label className="form-label">
                      Email <span>*</span>
                    </label>
                    <input
                      type="email"
                      className="form-control"
                      placeholder="Enter Email"
                    />
                  </div>
                  <div className="form-group">
                    <label className="form-label">
                      Password <span>*</span>
                    </label>
                    <div className="pass-group">
                      <input
                        type={passwordType}
                        onChange={handlePasswordChange} value={passwordInput}
                        className="form-control pass-input"
                        placeholder="Enter Password"
                      />
                      <span className="toggle-password"  onClick={togglePassword}>
                      {passwordType === "password" ? <span className="fas fa-eye"></span> : <span className="fas fa-eye-slash"></span>}
                      </span>
                    </div>
                  </div>
                  <div className="form-group">
                    <label className="form-label">
                      Confirm Password <span>*</span>
                    </label>
                    <div className="pass-group">
                      <input
                        type="password"
                        className="form-control"
                        placeholder="Enter Confirm Password"
                      />
                    </div>
                  </div>
                  <div className="form-group">
                    <label className="custom_check mt-0 mb-0">
                      <span>Remember me</span>
                      <input type="checkbox" name="remeber" />
                      <span className="checkmark" />
                    </label>
                  </div>
                  <Link
                    to={routes.login}
                    className="btn btn-outline-light w-100 btn-size"
                  >
                    Sign Up
                 </Link>
                  <div className="login-or">
                    <span className="span-or-log">
                      Or, Sign up with your email
                    </span>
                  </div>
                  {/* Social Login */}
                  <div className="social-login">
                    <Link
                      to="#"
                      className="d-flex align-items-center justify-content-center form-group btn google-login w-100"
                    >
                      <span>
                        <img
                          src="assets/img/icons/google.svg"
                          className="img-fluid"
                          alt="Google"
                        />
                      </span>
                      Sign up with Google
                   </Link>
                  </div>
                  <div className="social-login">
                    <Link
                      to="#"
                      className="mb-0 d-flex align-items-center justify-content-center form-group btn google-login w-100"
                    >
                      <span>
                        <img
                          src="assets/img/icons/facebook.svg"
                          className="img-fluid"
                          alt="Facebook"
                        />
                      </span>
                      Sign up with Facebook
                   </Link>
                  </div>
                  {/* /Social Login */}
                  <div className="text-center dont-have">
                    Already have login ? <Link to={routes.login}>Sign In</Link>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Register;

// angular/src/app/feature-module/authentication/register/register.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../shared/routes/routes';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrl: './register.component.scss'
})
export class RegisterComponent {
  public routes = routes
  public show_password = true;
  togglePassword() {
    this.show_password = !this.show_password;
  }

}

<div class="container">
  <!-- Header -->
  <header class="log-header">
    <a [routerLink]="routes.home"
      ><img class="img-fluid logo-dark" src="assets/img/logo.svg" alt="Logo"
    /></a>
  </header>
  <!-- /Header -->
  <div class="login-wrapper">
    <div class="loginbox">
      <div class="login-auth">
        <div class="login-auth-wrap">
          <h1>Signup! <span class="d-block"> New Account.</span></h1>
          <form >
            <div class="form-group">
              <label for="name" class="form-label">Name <span>*</span></label>
              <input
                type="text"
                class="form-control"
                placeholder="Enter Name"
              />
            </div>
            <div class="form-group">
              <label  for="email" class="form-label">Email <span>*</span></label>
              <input
                type="email"
                class="form-control"
                placeholder="Enter Email"
              />
            </div>
            <div class="form-group">
              <label for="password" class="form-label">Password <span>*</span></label>
              <div class="pass-group">
                <input
                  type="password"
                  class="form-control pass-input"
                  placeholder="Enter Password"
                  [type]="show_password ? 'password' : 'text'"
                />
                <span
                [ngClass]="
                  show_password === true
                    ? 'fas fa-eye-slash toggle-password'
                    : 'fas fa-eye toggle-password'
                "
                          (click)="togglePassword()"
                          (keydown.enter)="togglePassword()"
                          tabindex="0"
                          role="button"
                        ></span>
              </div>
            </div>
            <div class="form-group">
              <label for="confirmpassword" class="form-label">Confirm Password <span>*</span></label>
              <div class="pass-group">
                <input
                  type="password"
                  class="form-control"
                  placeholder="Enter Confirm Password"
                />
              </div>
            </div>
            <div class="form-group">
              <label class="custom_check mt-0 mb-0"
                ><span>Remember me</span>
                <input type="checkbox" name="remeber" />
                <span class="checkmark"></span>
              </label>
            </div>
            <a [routerLink]="routes.login" class="btn btn-outline-light w-100 btn-size"
              >Sign Up</a
            >
            <div class="login-or">
              <span class="span-or-log">Or, Sign up with your email</span>
            </div>
            <!-- Social Login -->
            <div class="social-login">
              <a
                href="javascript:void(0);"
                class="d-flex align-items-center justify-content-center form-group btn google-login w-100"
                ><span
                  ><img
                    src="assets/img/icons/google.svg"
                    class="img-fluid"
                    alt="Google" /></span
                >Sign up with Google</a
              >
            </div>
            <div class="social-login">
              <a
                href="javascript:void(0);"
                class="mb-0 d-flex align-items-center justify-content-center form-group btn google-login w-100"
                ><span
                  ><img
                    src="assets/img/icons/facebook.svg"
                    class="img-fluid"
                    alt="Facebook" /></span
                >Sign up with Facebook</a
              >
            </div>
            <!-- /Social Login -->
            <div class="text-center dont-have">
              Already have login ? <a [routerLink]="routes.login">Sign In</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
