// angular/src/app/feature-module/pages/maintenance/maintenance.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../shared/routes/routes';

@Component({
  selector: 'app-maintenance',
  templateUrl: './maintenance.component.html',
  styleUrl: './maintenance.component.scss'
})
export class MaintenanceComponent {
  public routes = routes

}

<div class="container">
    <!-- Header -->
    <header class="log-header">
        <a [routerLink]="routes.home"><img class="img-fluid logo-dark" src="assets/img/logo.svg" alt="Logo"></a>
    </header>
    <!-- /Header -->
    <div class="error-box">
        <img src="assets/img/maintenance.png" class="img-fluid" alt="Maintenance">
        <h1 class="coming-soon mb-2">We're Down for Maintenance</h1>
        <p>Our website is currently undergoing scheduled maintenance, will be right back in a few minutes.</p>
        <h6>We'll Be Back Shortly</h6>
        <div class="footer-social-links">
            <ul class="nav">						
                <li>
                    <a href="javascript:void(0);"><i class="fa-brands fa-instagram"></i></a>
                </li>						
                <li>
                    <a href="javascript:void(0);"><i class="fa-brands fa-twitter"></i> </a>
                </li>						
                <li>
                    <a href="javascript:void(0);"><i class="fab fa-youtube"></i></a>
                </li>
                <li>
                    <a href="javascript:void(0);"><i class="fa-brands fa-linkedin-in"></i></a>
                </li>
            </ul>
        </div>
        <a [routerLink]="routes.home" class="btn-maintance btn btn-primary">Back to Home</a>
    </div>
</div>

// react/src/feature-module/pages/maintenance/index.tsx
import React from "react";
import { Link } from "react-router-dom";
import ImageWithBasePath from "../../../core/img";
import { all_routes } from "../../router/all_routes";

const Maintenace = () => {
  const routes = all_routes;
  return (
    <div className="login-body">
      <div className="container">
        {/* Header */}
        <header className="log-header">
          <Link to={routes.home}>
            <ImageWithBasePath
              className="img-fluid logo-dark"
              src="assets/img/logo.svg"
              alt="Logo"
            />
          </Link>
        </header>
        {/* /Header */}
        <div className="error-box">
          <ImageWithBasePath
            src="assets/img/maintenance.png"
            className="img-fluid"
            alt="Maintenance"
          />
          <h1 className="coming-soon mb-2">We're Down for Maintenance</h1>
          <p>
            Our website is currently undergoing scheduled maintenance, will be
            right back in a few minutes.
          </p>
          <h6>We'll Be Back Shortly</h6>
          <div className="footer-social-links">
            <ul className="nav">
              <li>
                <Link to="#">
                  <i className="fa-brands fa-instagram" />
                </Link>
              </li>
              <li>
                <Link to="#">
                  <i className="fa-brands fa-twitter" />{" "}
                </Link>
              </li>
              <li>
                <Link to="#">
                  <i className="fab fa-youtube" />
                </Link>
              </li>
              <li>
                <Link to="#">
                  <i className="fa-brands fa-linkedin-in" />
                </Link>
              </li>
            </ul>
          </div>
          <Link to={routes.home} className="btn-maintance btn btn-primary">
            Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Maintenace;
