// angular/src/app/feature-module/blog/blog-grid/blog-grid.component.ts
import { Component, OnInit } from '@angular/core';
import { routes } from '../../../shared/routes/routes';
import * as AOS from 'aos';

@Component({
  selector: 'app-blog-grid',
  templateUrl: './blog-grid.component.html',
  styleUrl: './blog-grid.component.scss'
})
export class BlogGridComponent implements OnInit {
  public routes = routes;
  ngOnInit() {
    AOS.init({ disable: 'mobile', duration: 1200, once: true });
  }
}

<!-- Breadcrumb -->
<div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Blog Grid</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink] = "routes.home">Home </a></li>
                    <li>Blog Grid</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" alt="Line Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->		

<!-- Blog Grid-->
<div class="section blog-section">
    <div class="container">
        <div class="row">
            <div class="col-xl-4 col-lg-6 col-md-6">
                <!-- Blog -->
                <div class="blog-card" data-aos="fade-down" data-aos-duration="2000">
                    <div class="blog-img">
                        <a [routerLink] = "routes.blogDetails"><img src="assets/img/blog/blog-1.jpg" alt="Blog Image"></a>
                    </div>
                    <div class="blog-content">
                        <div class="blog-property">
                            <span>Property</span>
                        </div>
                        <div class="blog-title">
                            <h3><a [routerLink] = "routes.blogDetails">How to achieve financial independence</a></h3>
                            <p>There are many variations of passages of lorem ipsum available.</p>
                        </div>
                        <ul class="property-category d-flex justify-content-between align-items-center">
                            <li class="user-info">
                                <a href="javascript:void(0);"><img src="assets/img/profiles/avatar-01.jpg" class="img-fluid avatar" alt="User"></a>
                                <div class="user-name">
                                    <a href="javascript:void(0);">Rafael</a>
                                    <p>Posted on : 15 Jan 2023</p>
                                </div>													
                            </li>
                            <li>
                                <a [routerLink] = "routes.blogDetails"><span><i class='fa-solid fa-arrow-right'></i></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /Blog -->
            </div>
            <div class="col-xl-4 col-lg-6 col-md-6">
                <!-- Blog -->
                <div class="blog-card" data-aos="fade-down" data-aos-duration="2000">
                    <div class="blog-img">
                        <a [routerLink] = "routes.blogDetails"><img src="assets/img/blog/blog-2.jpg" alt="Blog Image"></a>
                    </div>
                    <div class="blog-content">
                        <div class="blog-property">
                            <span>Villa</span>
                        </div>
                        <div class="blog-title">
                            <h3><a [routerLink] = "routes.blogDetails">The most popular cities for homebuyers</a></h3>
                            <p>There are many variations of passages of lorem ipsum available.</p>
                        </div>
                        <ul class="property-category d-flex justify-content-between align-items-center">
                            <li class="user-info">
                                <a href="javascript:void(0);"><img src="assets/img/profiles/avatar-03.jpg" class="img-fluid avatar" alt="User"></a>
                                <div class="user-name">
                                    <a href="javascript:void(0);">John</a>
                                    <p>Posted on : 15 Jan 2023</p>
                                </div>													
                            </li>
                            <li>
                                <a [routerLink] = "routes.blogDetails"><span><i class='fa-solid fa-arrow-right'></i></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /Blog -->
            </div>
            <div class="col-xl-4 col-lg-6 col-md-6">
                <!-- Blog -->
                <div class="blog-card" data-aos="fade-down" data-aos-duration="2000">
                    <div class="blog-img">
                        <a [routerLink] = "routes.blogDetails"><img src="assets/img/blog/blog-3.jpg" alt="Blog Image"></a>
                    </div>
                    <div class="blog-content">
                        <div class="blog-property">
                            <span>Godown</span>
                        </div>
                        <div class="blog-title">
                            <h3><a [routerLink] = "routes.blogDetails">Learn how real estate really shapes our future</a></h3>
                            <p>There are many variations of passages of lorem ipsum available.</p>
                        </div>
                        <ul class="property-category d-flex justify-content-between align-items-center">
                            <li class="user-info">
                                <a href="javascript:void(0);"><img src="assets/img/profiles/avatar-05.jpg" class="img-fluid avatar" alt="User"></a>
                                <div class="user-name">
                                    <a href="javascript:void(0);">Eric Krok</a>
                                    <p>Posted on : 15 Jan 2023</p>
                                </div>													
                            </li>
                            <li>
                                <a [routerLink] = "routes.blogDetails"><span><i class='fa-solid fa-arrow-right'></i></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /Blog -->
            </div>
            
            <div class="col-xl-4 col-lg-6 col-md-6">
                <!-- Blog -->
                <div class="blog-card" data-aos="fade-down" data-aos-duration="2000">
                    <div class="blog-img">
                        <a [routerLink] = "routes.blogDetails"><img src="assets/img/blog/blog-4.jpg" alt="Image"></a>
                    </div>
                    <div class="blog-content">
                        <div class="blog-property">
                            <span>Factory</span>
                        </div>
                        <div class="blog-title">
                            <h3><a [routerLink] = "routes.blogDetails">30 Real Estate Blogs Every Realtor Should....</a></h3>
                            <p>There are many variations of passages of lorem ipsum available.</p>
                        </div>
                        <ul class="property-category d-flex justify-content-between align-items-center">
                            <li class="user-info">
                                <a href="javascript:void(0);"><img src="assets/img/profiles/avatar-07.jpg" class="img-fluid avatar" alt="User"></a>
                                <div class="user-name">
                                    <a href="javascript:void(0);">Anif</a>
                                    <p>Posted on : 15 Jan 2023</p>
                                </div>													
                            </li>
                            <li>
                                <a [routerLink] = "routes.blogDetails"><span><i class='fa-solid fa-arrow-right'></i></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /Blog -->
            </div>
            <div class="col-xl-4 col-lg-6 col-md-6">
                <!-- Blog -->
                <div class="blog-card" data-aos="fade-down" data-aos-duration="2000">
                    <div class="blog-img">
                        <a [routerLink] = "routes.blogDetails"><img src="assets/img/blog/blog-5.jpg" alt="Image"></a>
                    </div>
                    <div class="blog-content">
                        <div class="blog-property">
                            <span>Guest house</span>
                        </div>
                        <div class="blog-title">
                            <h3><a [routerLink] = "routes.blogDetails">Here Are Easy Ways To Know How To...</a></h3>
                            <p>There are many variations of passages of lorem ipsum available.</p>
                        </div>
                        <ul class="property-category d-flex justify-content-between align-items-center">
                            <li class="user-info">
                                <a href="javascript:void(0);"><img src="assets/img/profiles/avatar-08.jpg" class="img-fluid avatar" alt="Image"></a>
                                <div class="user-name">
                                    <a href="javascript:void(0);">Ramos</a>
                                    <p>Posted on : 14 Jan 2023</p>
                                </div>													
                            </li>
                            <li>
                                <a [routerLink] = "routes.blogDetails"><span><i class='fa-solid fa-arrow-right'></i></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /Blog -->
            </div>
            <div class="col-xl-4 col-lg-6 col-md-6">
                <!-- Blog -->
                <div class="blog-card aos" data-aos="fade-down" data-aos-duration="2000">
                    <div class="blog-img">
                        <a [routerLink] = "routes.blogDetails"><img src="assets/img/blog/blog-6.jpg" alt="Image"></a>
                    </div>
                    <div class="blog-content">
                        <div class="blog-property">
                            <span>House</span>
                        </div>
                        <div class="blog-title">
                            <h3><a [routerLink] = "routes.blogDetails">Importance of Virtual Reality in Real Estate</a></h3>
                            <p>There are many variations of passages of lorem ipsum available.</p>
                        </div>
                        <ul class="property-category d-flex justify-content-between align-items-center">
                            <li class="user-info">
                                <a href="javascript:void(0);"><img src="assets/img/profiles/avatar-10.jpg" class="img-fluid avatar" alt="User"></a>
                                <div class="user-name">
                                    <a href="javascript:void(0);">Patrick</a>
                                    <p>Posted on : 12 Jan 2023</p>
                                </div>													
                            </li>
                            <li>
                                <a [routerLink] = "routes.blogDetails"><span><i class='fa-solid fa-arrow-right'></i></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /Blog -->
            </div>
         </div>
    </div>				   
</div>	
<!-- /Blog Grid-->

// react/src/feature-module/blog/blogGrid/index.tsx
import React, { useEffect } from 'react'
import ImageWithBasePath from '../../../core/img'
import Aos from 'aos';
import BreadCrumb from '../../../core/common/breadCrumb'
;
import { Link } from 'react-router-dom';
import { all_routes } from '../../router/all_routes';
// import BreadCrumb from '../../../core/common/breadCrumb'
;

const BlogGrid = () => {
  const routes = all_routes
  useEffect(() => {
    Aos.init({ duration: 1200, once: true });
  }, []);

  return (
    <>
      {/* Breadcrumb */}
      <BreadCrumb title="Blog Grid" pageTitle="Home" />
      {/* Breadcrumb */}
      {/* Blog Grid*/}
      <div className="section blog-section">
        <div className="container">
          <div className="row">
            <div className="col-xl-4 col-lg-6 col-md-6">
              {/* Blog */}
              <div
                className="blog-card"
                data-aos="fade-down"
                data-aos-duration={2000}
              >
                <div className="blog-img">
                  <Link to={routes.blogDetails}>
                    <ImageWithBasePath src="assets/img/blog/blog-1.jpg" alt="Blog Image" />
                  </Link>
                </div>
                <div className="blog-content">
                  <div className="blog-property">
                    <span>Property</span>
                  </div>
                  <div className="blog-title">
                    <h3>
                      <Link to={routes.blogDetails}>
                        How to achieve financial independence
                      </Link>
                    </h3>
                    <p>
                      There are many variations of passages of lorem ipsum
                      available.
                    </p>
                  </div>
                  <ul className="property-category d-flex justify-content-between align-items-center">
                    <li className="user-info">
                      <Link to="#">
                        <ImageWithBasePath
                          src="assets/img/profiles/avatar-01.jpg"
                          className="img-fluid avatar"
                          alt="User"
                        />
                      </Link>
                      <div className="user-name">
                        <Link to="#">Rafael</Link>
                        <p>Posted on : 15 Jan 2023</p>
                      </div>
                    </li>
                    <li>
                      <Link to={routes.blogDetails}>
                        <span>
                          <i className="fa-solid fa-arrow-right" />
                        </span>
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
              {/* /Blog */}
            </div>
            <div className="col-xl-4 col-lg-6 col-md-6">
              {/* Blog */}
              <div
                className="blog-card"
                data-aos="fade-down"
                data-aos-duration={2000}
              >
                <div className="blog-img">
                  <Link to={routes.blogDetails}>
                    <ImageWithBasePath src="assets/img/blog/blog-2.jpg" alt="Blog Image" />
                  </Link>
                </div>
                <div className="blog-content">
                  <div className="blog-property">
                    <span>Villa</span>
                  </div>
                  <div className="blog-title">
                    <h3>
                      <Link to={routes.blogDetails}>
                        The most popular cities for homebuyers
                      </Link>
                    </h3>
                    <p>
                      There are many variations of passages of lorem ipsum
                      available.
                    </p>
                  </div>
                  <ul className="property-category d-flex justify-content-between align-items-center">
                    <li className="user-info">
                      <Link to="#">
                        <ImageWithBasePath
                          src="assets/img/profiles/avatar-03.jpg"
                          className="img-fluid avatar"
                          alt="User"
                        />
                      </Link>
                      <div className="user-name">
                        <Link to="#">John</Link>
                        <p>Posted on : 15 Jan 2023</p>
                      </div>
                    </li>
                    <li>
                      <Link to={routes.blogDetails}>
                        <span>
                          <i className="fa-solid fa-arrow-right" />
                        </span>
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
              {/* /Blog */}
            </div>
            <div className="col-xl-4 col-lg-6 col-md-6">
              {/* Blog */}
              <div
                className="blog-card"
                data-aos="fade-down"
                data-aos-duration={2000}
              >
                <div className="blog-img">
                  <Link to={routes.blogDetails}>
                    <ImageWithBasePath src="assets/img/blog/blog-3.jpg" alt="Blog Image" />
                  </Link>
                </div>
                <div className="blog-content">
                  <div className="blog-property">
                    <span>Godown</span>
                  </div>
                  <div className="blog-title">
                    <h3>
                      <Link to={routes.blogDetails}>
                        Learn how real estate really shapes our future
                      </Link>
                    </h3>
                    <p>
                      There are many variations of passages of lorem ipsum
                      available.
                    </p>
                  </div>
                  <ul className="property-category d-flex justify-content-between align-items-center">
                    <li className="user-info">
                      <Link to="#">
                        <ImageWithBasePath
                          src="assets/img/profiles/avatar-05.jpg"
                          className="img-fluid avatar"
                          alt="User"
                        />
                      </Link>
                      <div className="user-name">
                        <Link to="#">Eric Krok</Link>
                        <p>Posted on : 15 Jan 2023</p>
                      </div>
                    </li>
                    <li>
                      <Link to={routes.blogDetails}>
                        <span>
                          <i className="fa-solid fa-arrow-right" />
                        </span>
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
              {/* /Blog */}
            </div>
            <div className="col-xl-4 col-lg-6 col-md-6">
              {/* Blog */}
              <div
                className="blog-card"
                data-aos="fade-down"
                data-aos-duration={2000}
              >
                <div className="blog-img">
                  <Link to={routes.blogDetails}>
                    <ImageWithBasePath src="assets/img/blog/blog-4.jpg" alt="Image" />
                  </Link>
                </div>
                <div className="blog-content">
                  <div className="blog-property">
                    <span>Factory</span>
                  </div>
                  <div className="blog-title">
                    <h3>
                      <Link to={routes.blogDetails}>
                        30 Real Estate Blogs Every Realtor Should....
                      </Link>
                    </h3>
                    <p>
                      There are many variations of passages of lorem ipsum
                      available.
                    </p>
                  </div>
                  <ul className="property-category d-flex justify-content-between align-items-center">
                    <li className="user-info">
                      <Link to="#">
                        <ImageWithBasePath
                          src="assets/img/profiles/avatar-07.jpg"
                          className="img-fluid avatar"
                          alt="User"
                        />
                      </Link>
                      <div className="user-name">
                        <Link to="#">Anif</Link>
                        <p>Posted on : 15 Jan 2023</p>
                      </div>
                    </li>
                    <li>
                      <Link to={routes.blogDetails}>
                        <span>
                          <i className="fa-solid fa-arrow-right" />
                        </span>
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
              {/* /Blog */}
            </div>
            <div className="col-xl-4 col-lg-6 col-md-6">
              {/* Blog */}
              <div
                className="blog-card"
                data-aos="fade-down"
                data-aos-duration={2000}
              >
                <div className="blog-img">
                  <Link to={routes.blogDetails}>
                    <ImageWithBasePath src="assets/img/blog/blog-5.jpg" alt="Image" />
                  </Link>
                </div>
                <div className="blog-content">
                  <div className="blog-property">
                    <span>Guest house</span>
                  </div>
                  <div className="blog-title">
                    <h3>
                      <Link to={routes.blogDetails}>
                        Here Are Easy Ways To Know How To...
                      </Link>
                    </h3>
                    <p>
                      There are many variations of passages of lorem ipsum
                      available.
                    </p>
                  </div>
                  <ul className="property-category d-flex justify-content-between align-items-center">
                    <li className="user-info">
                      <Link to="#">
                        <ImageWithBasePath
                          src="assets/img/profiles/avatar-08.jpg"
                          className="img-fluid avatar"
                          alt="Image"
                        />
                      </Link>
                      <div className="user-name">
                        <Link to="#">Ramos</Link>
                        <p>Posted on : 14 Jan 2023</p>
                      </div>
                    </li>
                    <li>
                      <Link to={routes.blogDetails}>
                        <span>
                          <i className="fa-solid fa-arrow-right" />
                        </span>
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
              {/* /Blog */}
            </div>
            <div className="col-xl-4 col-lg-6 col-md-6">
              {/* Blog */}
              <div
                className="blog-card aos"
                data-aos="fade-down"
                data-aos-duration={2000}
              >
                <div className="blog-img">
                  <Link to={routes.blogDetails}>
                    <ImageWithBasePath src="assets/img/blog/blog-6.jpg" alt="Image" />
                  </Link>
                </div>
                <div className="blog-content">
                  <div className="blog-property">
                    <span>House</span>
                  </div>
                  <div className="blog-title">
                    <h3>
                      <Link to={routes.blogDetails}>
                        Importance of Virtual Reality in Real Estate
                      </Link>
                    </h3>
                    <p>
                      There are many variations of passages of lorem ipsum
                      available.
                    </p>
                  </div>
                  <ul className="property-category d-flex justify-content-between align-items-center">
                    <li className="user-info">
                      <Link to="#">
                        <ImageWithBasePath
                          src="assets/img/profiles/avatar-10.jpg"
                          className="img-fluid avatar"
                          alt="User"
                        />
                      </Link>
                      <div className="user-name">
                        <Link to="#">Patrick</Link>
                        <p>Posted on : 12 Jan 2023</p>
                      </div>
                    </li>
                    <li>
                      <Link to={routes.blogDetails}>
                        <span>
                          <i className="fa-solid fa-arrow-right" />
                        </span>
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
              {/* /Blog */}
            </div>
          </div>
        </div>
      </div>
      {/* /Blog Grid*/}
    </>
  )
}

export default BlogGrid
