// react/src/feature-module/agency/agencygridsidebar/index.tsx
import React from 'react'
import ImageWithBasePath from '../../../core/img'
import { Link } from 'react-router-dom'
import BreadCrumb from '../../../core/common/breadCrumb'

import { AgencySidebar } from '../agencysidebar'
import { all_routes } from '../../router/all_routes'

const AgencyGridSidebar = () => {
    const routes = all_routes
    return (
        <div>
            {/* Breadcrumb */}
            <BreadCrumb title="Agency Grid With Sidebar" pageTitle="Home" />
            {/* Breadcrumb */}
            {/* Content */}
            <div className="content">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-3 theiaStickySidebar">
                            <div className='stickybar'>
                            {/* Sidebar */}
                            <AgencySidebar/>
                            {/* /Sidebar */}
                            </div>
                        </div>
                        <div className="col-lg-9">
                            <div className="row">
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card agency card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agencyDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt="img"
                                                    src="assets/img/property/property-01.png"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>30 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>5.0</span>(20 Reviews)
                                                </p>
                                            </div>
                                            <div className="agency-user">
                                                <div className="agency-user-info">
                                                    <h6>
                                                        <Link to={routes.agencyDetails}>Luxurios Estate</Link>
                                                    </h6>
                                                    <p>
                                                        <i className="bx bx-map" />
                                                        New York, Queens
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card agency card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agencyDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt="img"
                                                    src="assets/img/property/property-02.png"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>50 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>4.0</span>(12 Reviews)
                                                </p>
                                            </div>
                                            <div className="agency-user">
                                                <div className="agency-user-info">
                                                    <h6>
                                                        <Link to={routes.agencyDetails}>Green Reality</Link>
                                                    </h6>
                                                    <p>
                                                        <i className="bx bx-map" />
                                                        City Center, Manhattan
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card agency card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agencyDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt="img"
                                                    src="assets/img/property/property-03.png"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>25 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star" />
                                                    <i className="fa-solid fa-star" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>3.0</span>(10 Reviews)
                                                </p>
                                            </div>
                                            <div className="agency-user">
                                                <div className="agency-user-info">
                                                    <h6>
                                                        <Link to={routes.agencyDetails}>Homes</Link>
                                                    </h6>
                                                    <p>
                                                        <i className="bx bx-map" />
                                                        Las Vegas
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card agency card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agencyDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt="img"
                                                    src="assets/img/property/property-05.png"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>38 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star" />
                                                    <i className="fa-solid fa-star" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>3.0</span>(35 Reviews)
                                                </p>
                                            </div>
                                            <div className="agency-user">
                                                <div className="agency-user-info">
                                                    <h6>
                                                        <Link to={routes.agencyDetails}>Queen Estate</Link>
                                                    </h6>
                                                    <p>
                                                        <i className="bx bx-map" />
                                                        Pawnee City, NE
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card agency card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agencyDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt="img"
                                                    src="assets/img/property/property-04.png"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>45 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>5.0</span>(15 Reviews)
                                                </p>
                                            </div>
                                            <div className="agency-user">
                                                <div className="agency-user-info">
                                                    <h6>
                                                        <Link to={routes.agencyDetails}>Rent a Home</Link>
                                                    </h6>
                                                    <p>
                                                        <i className="bx bx-map" />
                                                        Barron, WI
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Agent */}
                                <div className="col-xl-4 col-lg-6 col-md-6 d-flex">
                                    <div className="agent-card agency card flex-fill">
                                        <div className="agent-img">
                                            <Link to={routes.agencyDetails} className="property-img">
                                                <ImageWithBasePath
                                                    className="img-fluid"
                                                    alt="img"
                                                    src="assets/img/property/property-06.png"
                                                />
                                            </Link>
                                            <div className="list-feature">
                                                <span>35 Listings</span>
                                            </div>
                                        </div>
                                        <div className="agent-content">
                                            <div className="rating">
                                                <span className="rating-count">
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                    <i className="fa-solid fa-star checked" />
                                                </span>
                                                <p className="rating-review">
                                                    <span>5.0</span>(18 Reviews)
                                                </p>
                                            </div>
                                            <div className="agency-user">
                                                <div className="agency-user-info">
                                                    <h6>
                                                        <Link to={routes.agencyDetails}>Louis Realtors</Link>
                                                    </h6>
                                                    <p>
                                                        <i className="bx bx-map" />
                                                        Correll, MN
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {/* /Agent */}
                                {/* Pagination */}
                                <div className="col-lg-12">
                                    <div className="grid-pagination">
                                        <ul className="pagination justify-content-center">
                                            <li className="page-item prev">
                                                <Link className="page-link" to="#">
                                                    <i className="fa-solid fa-arrow-left" /> Prev
                                                </Link>
                                            </li>
                                            <li className="page-item">
                                                <Link className="page-link" to="#">
                                                    1
                                                </Link>
                                            </li>
                                            <li className="page-item active">
                                                <Link className="page-link" to="#">
                                                    2
                                                </Link>
                                            </li>
                                            <li className="page-item">
                                                <Link className="page-link" to="#">
                                                    3
                                                </Link>
                                            </li>
                                            <li className="page-item">
                                                <Link className="page-link" to="#">
                                                    4
                                                </Link>
                                            </li>
                                            <li className="page-item next">
                                                <Link className="page-link" to="#">
                                                    Next <i className="fa-solid fa-arrow-right" />
                                                </Link>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                {/* /Pagination */}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {/* /Content */}
        </div>
    )
}

export default AgencyGridSidebar

// angular/src/app/feature-module/agency/agency-grid-sidebar/agency-grid-sidebar.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../shared/routes/routes';

@Component({
  selector: 'app-agency-grid-sidebar',
  templateUrl: './agency-grid-sidebar.component.html',
  styleUrl: './agency-grid-sidebar.component.scss'
})
export class AgencyGridSidebarComponent {
  public routes = routes

}


  <!-- Breadcrumb -->
  <div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Agency Grid With Sidebar</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink]="routes.home">Home </a></li>
                    <li>Agency Grid With Sidebar</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" class="img-fluid" alt="Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->

<!-- Content -->
<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 theiaStickySidebar">
                <div class="stickybar">
                <!-- Sidebar -->
                <div class="left-sidebar-widget">
                    <div class="collapse-card">
                        <h4 class="card-title">
                            <a class="collapsed" data-bs-toggle="collapse" href="#search" aria-expanded="false">Search</a>
                        </h4>
                        <div id="search" class="card-collapse collapse show">
                            <ul class="show-list">
                                <li class="review-form">
                                    <label for="agencyname">Agency  Name</label>
                                    <input type="text" class="form-control" placeholder="Enter Name">
                                </li>
                                <li class="review-form">
                                    <label for="agencytype">Agency  Type</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="2">Luxurios Estate</mat-option>
                                        <mat-option value="3">Green Reality</mat-option>
                                    </mat-select>
                                </li>
                                <li class="review-form">
                                    <label for="city">Select City</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="2">Texas</mat-option>
                                        <mat-option value="3">New Yor</mat-option>
                                    </mat-select>
                                </li>
                                <li class="review-form">
                                    <label for="area">Select Area</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="2">Oakley</mat-option>
                                        <mat-option value="3">Park Ave</mat-option>
                                    </mat-select>
                                </li>
                                <li class="review-form">
                                    <label for="category">Select Category</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="2">Villa</mat-option>
                                        <mat-option value="3">Apartment</mat-option>
                                    </mat-select>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="collapse-card">
                        <h4 class="card-title">
                            <a class="collapsed" data-bs-toggle="collapse" href="#categiries" aria-expanded="false">Categories</a>
                        </h4>
                        <div id="categiries" class="card-collapse collapse show">
                            <ul class="checkbox-list">
                                <li>
                                    <label class="custom_check">
                                        <input type="checkbox" name="username">
                                        <span class="checkmark"></span>  Rental (41) 
                                    </label>
                                </li>
                                <li>
                                    <label class="custom_check">
                                        <input type="checkbox" name="username">
                                        <span class="checkmark"></span> Sales  (15)
                                    </label>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /Sidebar -->
                </div>
            </div>
            
            <div class="col-lg-9">
                <div class="row">
                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">                           
                        <div class="agent-card agency card flex-fill">
                            <div class="agent-img">
                                <a [routerLink]="routes.agencyDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/property/property-01.png">
                                </a>
                                <div class="list-feature">
                                    <span>30 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <p class="rating-review"><span>5.0</span>(20 Reviews)</p>
                                </div>
                                <div class="agency-user">
                                    <div class="agency-user-info">
                                        <h6>
                                            <a [routerLink]="routes.agencyDetails">Luxurios Estate</a> 
                                        </h6>
                                        <p><i class="bx bx-map"></i>New York, Queens</p>
                                    </div>
                                </div>
                            </div>	
                        </div>
                    </div>
                    <!-- /Agent -->

                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">                           
                        <div class="agent-card agency card flex-fill">
                            <div class="agent-img">
                                <a [routerLink]="routes.agencyDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/property/property-02.png">
                                </a>
                                <div class="list-feature">
                                    <span>50 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star"></i>
                                    </span>
                                    <p class="rating-review"><span>4.0</span>(12 Reviews)</p>
                                </div>
                                <div class="agency-user">
                                    <div class="agency-user-info">
                                        <h6>
                                            <a [routerLink]="routes.agencyDetails">Green Reality</a> 
                                        </h6>
                                        <p><i class="bx bx-map"></i>City Center, Manhattan</p>
                                    </div>
                                </div>
                            </div>	
                        </div>
                    </div>
                    <!-- /Agent -->

                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">                           
                        <div class="agent-card agency card flex-fill">
                            <div class="agent-img">
                                <a [routerLink]="routes.agencyDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/property/property-03.png">
                                </a>
                                <div class="list-feature">
                                    <span>25 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star"></i>
                                        <i class="fa-solid fa-star"></i>
                                    </span>
                                    <p class="rating-review"><span>3.0</span>(10 Reviews)</p>
                                </div>
                                <div class="agency-user">
                                    <div class="agency-user-info">
                                        <h6>
                                            <a [routerLink]="routes.agencyDetails">Homes</a> 
                                        </h6>
                                        <p><i class="bx bx-map"></i>Las Vegas</p>
                                    </div>
                                </div>
                            </div>	
                        </div>
                    </div>
                    <!-- /Agent -->

                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">                           
                        <div class="agent-card agency card flex-fill">
                            <div class="agent-img">
                                <a [routerLink]="routes.agencyDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/property/property-05.png">
                                </a>
                                <div class="list-feature">
                                    <span>38 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star"></i>
                                        <i class="fa-solid fa-star"></i>
                                    </span>
                                    <p class="rating-review"><span>3.0</span>(35 Reviews)</p>
                                </div>
                                <div class="agency-user">
                                    <div class="agency-user-info">
                                        <h6>
                                            <a [routerLink]="routes.agencyDetails">Queen Estate</a> 
                                        </h6>
                                        <p><i class="bx bx-map"></i>Pawnee City, NE</p>
                                    </div>
                                </div>
                            </div>	
                        </div>
                    </div>
                    <!-- /Agent -->

                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">                           
                        <div class="agent-card agency card flex-fill">
                            <div class="agent-img">
                                <a [routerLink]="routes.agencyDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/property/property-04.png">
                                </a>
                                <div class="list-feature">
                                    <span>45 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <p class="rating-review"><span>5.0</span>(15 Reviews)</p>
                                </div>
                                <div class="agency-user">
                                    <div class="agency-user-info">
                                        <h6>
                                            <a [routerLink]="routes.agencyDetails">Rent a Home</a> 
                                        </h6>
                                        <p><i class="bx bx-map"></i>Barron, WI</p>
                                    </div>
                                </div>
                            </div>	
                        </div>
                    </div>
                    <!-- /Agent -->
                    
                    <!-- Agent -->
                    <div class="col-xl-4 col-lg-6 col-md-6 d-flex">                           
                        <div class="agent-card agency card flex-fill">
                            <div class="agent-img">
                                <a [routerLink]="routes.agencyDetails" class="property-img">
                                    <img class="img-fluid" alt="Property Image" src="assets/img/property/property-06.png">
                                </a>
                                <div class="list-feature">
                                    <span>35 Listings</span>
                                </div>
                            </div>
                            <div class="agent-content">
                                <div class="rating">
                                    <span class="rating-count">
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                        <i class="fa-solid fa-star checked"></i>
                                    </span>
                                    <p class="rating-review"><span>5.0</span>(18 Reviews)</p>
                                </div>
                                <div class="agency-user">
                                    <div class="agency-user-info">
                                        <h6>
                                            <a [routerLink]="routes.agencyDetails">Louis Realtors</a> 
                                        </h6>
                                        <p><i class="bx bx-map"></i>Correll, MN</p>
                                    </div>
                                </div>
                            </div>	
                        </div>
                    </div>
                    <!-- /Agent -->
                    
                    <!-- Pagination -->
                    <div class="col-lg-12"> 
                        <div class="grid-pagination">
                            <ul class="pagination justify-content-center">
                                <li class="page-item prev">
                                    <a class="page-link" href="javascript:void(0);"><i class="fa-solid fa-arrow-left"></i> Prev</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="javascript:void(0);">1</a>
                                </li>
                                <li class="page-item active">
                                    <a class="page-link" href="javascript:void(0);">2</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="javascript:void(0);">3</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="javascript:void(0);">4</a>
                                </li>
                                <li class="page-item next">
                                    <a class="page-link" href="javascript:void(0);">Next <i class="fa-solid fa-arrow-right"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /Pagination -->

                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Content -->
