// react/src/feature-module/agent/agentGrid/index.tsx
import React from 'react'
import ImageWithBasePath from '../../../core/img'
import { Link } from 'react-router-dom'
import { agentType, area, city, customStyles, propertCategory } from '../../../core/common/select'
import Select from 'react-select'
import BreadCrumb from '../../../core/common/breadCrumb'
import { all_routes } from '../../router/all_routes'

const AgentGrid = () => {
    const routes = all_routes
    return (
        <>
            {/* Breadcrumb */}
            <BreadCrumb title="Agent Grid Without Sidebar" pageTitle="Home" />
            {/* Breadcrumb */}
            {/* Content */}
            <div className="listing-section">
                <div className="container">
                    {/* Show Result */}
                    <div className="showing-result-head show-list">
                        <div className="row">
                            <div className="col-lg-3 col-md-6">
                                <div className="review-form">
                                    <label>Agent Type</label>
                                    <Select options={agentType} defaultValue={agentType[0]} className="select" styles={customStyles} />
                                </div>
                            </div>
                            <div className="col-lg-3 col-md-6">
                                <div className="review-form">
                                    <label>Select City</label>
                                    <Select options={city} defaultValue={city[0]} className="select" styles={customStyles} />

                                </div>
                            </div>
                            <div className="col-lg-3 col-md-6">
                                <div className="review-form">
                                    <label>Select Area</label>
                                    <Select options={area} defaultValue={area[0]} className="select" styles={customStyles} />

                                </div>
                            </div>
                            <div className="col-lg-3 col-md-6">
                                <div className="review-form">
                                    <label>Select Category</label>
                                   
                                    <Select options={propertCategory} defaultValue={propertCategory[0]} className="select" styles={customStyles} />

                                </div>
                            </div>
                        </div>
                    </div>
                    {/* /Show Result */}
                    <div className="row">
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agentDetails} className="property-img">
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/agents/agent-01.jpg"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>30 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                        </span>
                                        <p className="rating-review">
                                            <span>5.0</span>(20 Reviews)
                                        </p>
                                    </div>
                                    <h6>
                                        <Link to={routes.agentDetails}>Mike Rutter</Link>
                                    </h6>
                                    <p>
                                        <i className="bx bx-user-voice" />
                                        Selling Agent
                                    </p>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agentDetails} className="property-img">
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/agents/agent-02.jpg"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>40 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                        </span>
                                        <p className="rating-review">
                                            <span>5.0</span>(18 Reviews)
                                        </p>
                                    </div>
                                    <h6>
                                        <Link to={routes.agentDetails}>Pamela</Link>
                                    </h6>
                                    <p>
                                        <i className="bx bx-user-voice" />
                                        Buying Agent
                                    </p>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agentDetails} className="property-img">
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/agents/agent-03.jpg"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>50 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                        </span>
                                        <p className="rating-review">
                                            <span>5.0</span>(12 Reviews)
                                        </p>
                                    </div>
                                    <h6>
                                        <Link to={routes.agentDetails}>Enriquez</Link>
                                    </h6>
                                    <p>
                                        <i className="bx bx-user-voice" />
                                        Selling Agent
                                    </p>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agentDetails} className="property-img">
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/agents/agent-04.jpg"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>45 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                        </span>
                                        <p className="rating-review">
                                            <span>5.0</span>(22 Reviews)
                                        </p>
                                    </div>
                                    <h6>
                                        <Link to={routes.agentDetails}>Lowe</Link>
                                    </h6>
                                    <p>
                                        <i className="bx bx-user-voice" />
                                        Selling Agent
                                    </p>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agentDetails} className="property-img">
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/agents/agent-05.jpg"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>32 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                        </span>
                                        <p className="rating-review">
                                            <span>5.0</span>(13 Reviews)
                                        </p>
                                    </div>
                                    <h6>
                                        <Link to={routes.agentDetails}>Gregory</Link>
                                    </h6>
                                    <p>
                                        <i className="bx bx-user-voice" />
                                        Buying Agent
                                    </p>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agentDetails} className="property-img">
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/agents/agent-06.jpg"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>60 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                        </span>
                                        <p className="rating-review">
                                            <span>5.0</span>(10 Reviews)
                                        </p>
                                    </div>
                                    <h6>
                                        <Link to={routes.agentDetails}>Lee</Link>
                                    </h6>
                                    <p>
                                        <i className="bx bx-user-voice" />
                                        Selling Agent
                                    </p>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                    </div>
                </div>
            </div>
            {/* /Content */}
        </>

    )
}

export default AgentGrid

// angular/src/app/feature-module/agent/agent-grid/agent-grid.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../shared/routes/routes';

@Component({
  selector: 'app-agent-grid',
  templateUrl: './agent-grid.component.html',
  styleUrl: './agent-grid.component.scss'
})
export class AgentGridComponent {
  public routes = routes;
}

<!-- Breadcrumb -->
<div class="breadcrumb">
    <div class="container">
        <div class="bread-crumb-head">
            <div class="breadcrumb-title">
                <h2>Agent Grid Without Sidebar</h2>
            </div>
            <div class="breadcrumb-list">
                <ul>
                    <li><a [routerLink] = "routes.home">Home </a></li>
                    <li>Agent Grid Without Sidebar</li>
                </ul>
            </div>
        </div>
        <div class="breadcrumb-border-img">
            <img src="assets/img/bg/line-bg.png" class="img-fluid" alt="Image">
        </div>
    </div>
</div>
<!-- Breadcrumb -->

<!-- Content -->
<div class="listing-section">
    <div class="container">

        <!-- Show Result -->
        <div class="showing-result-head show-list">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="review-form">
                          <label for="Agent Type">Agent Type</label>
                        <mat-select class="custom-mat-select" placeholder="Select">
                            <mat-option value="Selling Agent">Selling Agent</mat-option>
                            <mat-option value="Buying Agent">Buying Agent</mat-option>
                        </mat-select>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="review-form">
                          <label for="Select City">Select City</label>
                        <mat-select class="custom-mat-select" placeholder="Select">
                            <mat-option value="Texas">Texas</mat-option>
                            <mat-option value="New York">New York</mat-option>
                        </mat-select>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="review-form">
                        <label for="Select Area">Select Area</label>
                        <mat-select class="custom-mat-select" placeholder="Select">
                            <mat-option value="Select">Select</mat-option>
                            <mat-option value="Oakley">Oakley</mat-option>
                            <mat-option value="Park Ave">Park Ave</mat-option>
                        </mat-select>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="review-form">
                        <label for="Select Category">Select Category</label>
                        <mat-select class="custom-mat-select" placeholder="Select">
                            <mat-option value="Villa">Villa</mat-option>
                            <mat-option value="Apartment">Apartment</mat-option>
                        </mat-select>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Show Result -->

        <div class="row">

            <!-- Agent -->
            <div class="col-lg-4 col-md-6 d-flex">
                <div class="agent-card card flex-fill">
                    <div class="agent-img">
                        <a [routerLink] = "routes.agentDetails" class="property-img">
                            <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-01.jpg">
                        </a>
                        <div class="list-feature">
                            <span>30 Listings</span>
                        </div>
                    </div>
                    <div class="agent-content">
                        <div class="rating">
                            <span class="rating-count">
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                            </span>
                            <p class="rating-review"><span>5.0</span>(20 Reviews)</p>
                        </div>
                        <h6>
                            <a [routerLink] = "routes.agentDetails">Mike Rutter</a>
                        </h6>
                        <p><i class="bx bx-user-voice"></i>Selling Agent</p>
                    </div>
                </div>
            </div>
            <!-- /Agent -->

            <!-- Agent -->
            <div class="col-lg-4 col-md-6 d-flex">
                <div class="agent-card card flex-fill">
                    <div class="agent-img">
                        <a [routerLink] = "routes.agentDetails" class="property-img">
                            <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-02.jpg">
                        </a>
                        <div class="list-feature">
                            <span>40 Listings</span>
                        </div>
                    </div>
                    <div class="agent-content">
                        <div class="rating">
                            <span class="rating-count">
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                            </span>
                            <p class="rating-review"><span>5.0</span>(18 Reviews)</p>
                        </div>
                        <h6>
                            <a [routerLink] = "routes.agentDetails">Pamela</a>
                        </h6>
                        <p><i class="bx bx-user-voice"></i>Buying Agent</p>
                    </div>
                </div>
            </div>
            <!-- /Agent -->

            <!-- Agent -->
            <div class="col-lg-4 col-md-6 d-flex">
                <div class="agent-card card flex-fill">
                    <div class="agent-img">
                        <a [routerLink] = "routes.agentDetails" class="property-img">
                            <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-03.jpg">
                        </a>
                        <div class="list-feature">
                            <span>50 Listings</span>
                        </div>
                    </div>
                    <div class="agent-content">
                        <div class="rating">
                            <span class="rating-count">
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                            </span>
                            <p class="rating-review"><span>5.0</span>(12 Reviews)</p>
                        </div>
                        <h6>
                            <a [routerLink] = "routes.agentDetails">Enriquez</a>
                        </h6>
                        <p><i class="bx bx-user-voice"></i>Selling Agent</p>
                    </div>
                </div>
            </div>
            <!-- /Agent -->

            <!-- Agent -->
            <div class="col-lg-4 col-md-6 d-flex">
                <div class="agent-card card flex-fill">
                    <div class="agent-img">
                        <a [routerLink] = "routes.agentDetails" class="property-img">
                            <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-04.jpg">
                        </a>
                        <div class="list-feature">
                            <span>45 Listings</span>
                        </div>
                    </div>
                    <div class="agent-content">
                        <div class="rating">
                            <span class="rating-count">
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                            </span>
                            <p class="rating-review"><span>5.0</span>(22 Reviews)</p>
                        </div>
                        <h6>
                            <a [routerLink] = "routes.agentDetails">Lowe</a>
                        </h6>
                        <p><i class="bx bx-user-voice"></i>Selling Agent</p>
                    </div>
                </div>
            </div>
            <!-- /Agent -->

            <!-- Agent -->
            <div class="col-lg-4 col-md-6 d-flex">
                <div class="agent-card card flex-fill">
                    <div class="agent-img">
                        <a [routerLink] = "routes.agentDetails" class="property-img">
                            <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-05.jpg">
                        </a>
                        <div class="list-feature">
                            <span>32 Listings</span>
                        </div>
                    </div>
                    <div class="agent-content">
                        <div class="rating">
                            <span class="rating-count">
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                            </span>
                            <p class="rating-review"><span>5.0</span>(13 Reviews)</p>
                        </div>
                        <h6>
                            <a [routerLink] = "routes.agentDetails">Gregory</a>
                        </h6>
                        <p><i class="bx bx-user-voice"></i>Buying Agent</p>
                    </div>
                </div>
            </div>
            <!-- /Agent -->

            <!-- Agent -->
            <div class="col-lg-4 col-md-6 d-flex">
                <div class="agent-card card flex-fill">
                    <div class="agent-img">
                        <a [routerLink] = "routes.agentDetails" class="property-img">
                            <img class="img-fluid" alt="Property Image" src="assets/img/agents/agent-06.jpg">
                        </a>
                        <div class="list-feature">
                            <span>60 Listings</span>
                        </div>
                    </div>
                    <div class="agent-content">
                        <div class="rating">
                            <span class="rating-count">
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                                <i class="fa-solid fa-star checked"></i>
                            </span>
                            <p class="rating-review"><span>5.0</span>(10 Reviews)</p>
                        </div>
                        <h6>
                            <a [routerLink] = "routes.agentDetails">Lee</a>
                        </h6>
                        <p><i class="bx bx-user-voice"></i>Selling Agent</p>
                    </div>
                </div>
            </div>
            <!-- /Agent -->
        </div>
    </div>
</div>
<!-- /Content -->
