// react/src/feature-module/agency/agencygrid/index.tsx
import React from 'react'
import ImageWithBasePath from '../../../core/img'
import { Link } from 'react-router-dom'
import BreadCrumb from '../../../core/common/breadCrumb'

import { agenctType, area, city, customStyles, propertCategory } from '../../../core/common/select'
import Select from 'react-select';
import { all_routes } from '../../router/all_routes'
const AgencyGrid = () => {
    const routes = all_routes
    return (
        <>
            {/* Breadcrumb */}
            <BreadCrumb title="Agency Grid Without Sidebar" pageTitle="Home" />
            {/* Breadcrumb */}
            {/* Content */}
            <div className="listing-section">
                <div className="container">
                    {/* Show Result */}
                    <div className="showing-result-head show-list">
                        <div className="row">
                            <div className="col-lg-3 col-md-6">
                                <div className="review-form">
                                    <label>Agency Type</label>
                                    <Select options={agenctType} defaultValue={agenctType[0]} className="select" styles={customStyles} />

                                </div>
                            </div>
                            <div className="col-lg-3 col-md-6">
                                <div className="review-form">
                                    <label>Select City</label>
                                    <Select options={city} defaultValue={city[0]} className="select" styles={customStyles} />

                                </div>
                            </div>
                            <div className="col-lg-3 col-md-6">
                                <div className="review-form">
                                    <label>Select Area</label>
                                    <Select options={area} defaultValue={area[0]} className="select" styles={customStyles} />

                                </div>
                            </div>
                            <div className="col-lg-3 col-md-6">
                                <div className="review-form">
                                    <label>Select Category</label>
                                    <Select options={propertCategory} defaultValue={propertCategory[0]} className="select" styles={customStyles} />

                                </div>
                            </div>
                        </div>
                    </div>
                    {/* Show Result */}
                    <div className="row">
                        {/* Agency */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card agency card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agencyDetails}>
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/property/property-01.png"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>30 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                        </span>
                                        <p className="rating-review">
                                            <span>5.0</span>(20 Reviews)
                                        </p>
                                    </div>
                                    <div className="agency-user">
                                        <div className="agency-user-info">
                                            <h6>
                                                <Link to={routes.agencyDetails}>Luxurios Estate</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-map" />
                                                New York, Queens
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {/* /Agency */}
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card agency card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agencyDetails}>
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/property/property-02.png"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>70 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star" />
                                        </span>
                                        <p className="rating-review">
                                            <span>4.0</span>(12 Reviews)
                                        </p>
                                    </div>
                                    <div className="agency-user">
                                        <div className="agency-user-info">
                                            <h6>
                                                <Link to={routes.agencyDetails}>Green Reality</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-map" />
                                                City Center, Manhattan
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card agency card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agencyDetails}>
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/property/property-03.png"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>50 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star" />
                                            <i className="fa-solid fa-star" />
                                        </span>
                                        <p className="rating-review">
                                            <span>3.0</span>(10 Reviews)
                                        </p>
                                    </div>
                                    <div className="agency-user">
                                        <div className="agency-user-info">
                                            <h6>
                                                <Link to={routes.agencyDetails}>Homes</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-map" />
                                                Las Vegas
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card agency card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agencyDetails}>
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/property/property-05.png"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>55 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                        </span>
                                        <p className="rating-review">
                                            <span>5.0</span>(15 Reviews)
                                        </p>
                                    </div>
                                    <div className="agency-user">
                                        <div className="agency-user-info">
                                            <h6>
                                                <Link to={routes.agencyDetails}>Queen Estate</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-map" />
                                                Pawnee City, NE
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card agency card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agencyDetails}>
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/property/property-04.png"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>44 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                        </span>
                                        <p className="rating-review">
                                            <span>5.0</span>(23 Reviews)
                                        </p>
                                    </div>
                                    <div className="agency-user">
                                        <div className="agency-user-info">
                                            <h6>
                                                <Link to={routes.agencyDetails}>Rent a Home</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-map" />
                                                Barron, WI
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                        {/* Agent */}
                        <div className="col-lg-4 col-md-6 d-flex">
                            <div className="agent-card agency card flex-fill">
                                <div className="agent-img">
                                    <Link to={routes.agencyDetails}>
                                        <ImageWithBasePath
                                            className="img-fluid"
                                            alt='img'
                                            src="assets/img/property/property-06.png"
                                        />
                                    </Link>
                                    <div className="list-feature">
                                        <span>60 Listings</span>
                                    </div>
                                </div>
                                <div className="agent-content">
                                    <div className="rating">
                                        <span className="rating-count">
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                            <i className="fa-solid fa-star checked" />
                                        </span>
                                        <p className="rating-review">
                                            <span>5.0</span>(25 Reviews)
                                        </p>
                                    </div>
                                    <div className="agency-user">
                                        <div className="agency-user-info">
                                            <h6>
                                                <Link to={routes.agencyDetails}>Louis Realtors</Link>
                                            </h6>
                                            <p>
                                                <i className="bx bx-map" />
                                                Correll, MN
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {/* /Agent */}
                    </div>
                </div>
            </div>
            {/* /Content */}
        </>

    )
}

export default AgencyGrid

// angular/src/app/feature-module/agency/agency-grid/agency-grid.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../shared/routes/routes';

@Component({
  selector: 'app-agency-grid',
  templateUrl: './agency-grid.component.html',
  styleUrl: './agency-grid.component.scss'
})
export class AgencyGridComponent {
  public routes = routes

}


            <!-- Breadcrumb -->
            <div class="breadcrumb">
                <div class="container">
                    <div class="bread-crumb-head">
                        <div class="breadcrumb-title">
                            <h2>Agency Grid Without Sidebar</h2>
                        </div>
                        <div class="breadcrumb-list">
                            <ul>
                                <li><a [routerLink]="routes.home">Home </a></li>
                                <li>Agency Grid Without Sidebar</li>
                            </ul>
                        </div>
                    </div>
                    <div class="breadcrumb-border-img">
                        <img src="assets/img/bg/line-bg.png" class="img-fluid" alt="Image">
                    </div>
                </div>
            </div>
            <!-- Breadcrumb -->

            <!-- Content -->
			<div class="listing-section">
				<div class="container">
				
					<!-- Show Result -->
                    <div class="showing-result-head show-list">
                        <div class="row">
                            <div class="col-lg-3 col-md-6">
                                <div class="review-form">
                                    <label for="type">Agency Type</label>
                                    
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="2">Luxurios Estate</mat-option>
                                        <mat-option value="3">Green Reality</mat-option>
                                    </mat-select>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6">
                                <div class="review-form">
                                    <label for="town">Select City</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="2">Texas</mat-option>
                                        <mat-option value="3">New Yor</mat-option>
                                    </mat-select>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6">
                                <div class="review-form">
                                    <label for="area">Select Area</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="2">Oakley</mat-option>
                                        <mat-option value="3">Park Ave</mat-option>
                                    </mat-select>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6">
                                <div class="review-form">
                                    <label for="category">Select Category</label>
                                    <mat-select class="custom-mat-select" placeholder="Select">
                                        <mat-option value="1">Select</mat-option>
                                        <mat-option value="2">Villa</mat-option>
                                        <mat-option value="3">Apartment</mat-option>
                                    </mat-select>
                                </div>
                            </div>
                        </div> 
                    </div>
					<!-- Show Result -->
					
					<div class="row">

                        <!-- Agency -->
						<div class="col-lg-4 col-md-6 d-flex">                           
                            <div class="agent-card agency card flex-fill">
                                <div class="agent-img">
                                    <a [routerLink]="routes.agencyDetails">
                                        <img class="img-fluid" alt="Property Image" src="assets/img/property/property-01.png">
                                    </a>
                                    <div class="list-feature">
                                        <span>30 Listings</span>
                                    </div>
                                </div>
                                <div class="agent-content">
                                    <div class="rating">
										<span class="rating-count">
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
										</span>
                                        <p class="rating-review"><span>5.0</span>(20 Reviews)</p>
                                    </div>
									<div class="agency-user">
										<div class="agency-user-info">
											<h6>
												<a [routerLink]="routes.agencyDetails">Luxurios Estate</a> 
											</h6>
											<p><i class="bx bx-map"></i>New York, Queens</p>
										</div>
									</div>
                                </div>	
                            </div>
						</div>
                        <!-- /Agency -->

                        <!-- Agent -->
						<div class="col-lg-4 col-md-6 d-flex">                           
                            <div class="agent-card agency card flex-fill">
                                <div class="agent-img">
                                    <a [routerLink]="routes.agencyDetails">
                                        <img class="img-fluid" alt="Property Image" src="assets/img/property/property-02.png">
                                    </a>
                                    <div class="list-feature">
                                        <span>70 Listings</span>
                                    </div>
                                </div>
                                <div class="agent-content">
                                    <div class="rating">
										<span class="rating-count">
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star"></i>
										</span>
                                        <p class="rating-review"><span>4.0</span>(12 Reviews)</p>
                                    </div>
									<div class="agency-user">
										<div class="agency-user-info">
											<h6>
												<a [routerLink]="routes.agencyDetails">Green Reality</a> 
											</h6>
											<p><i class="bx bx-map"></i>City Center, Manhattan</p>
										</div>
									</div>
                                </div>	
                            </div>
						</div>
                        <!-- /Agent -->

                        <!-- Agent -->
						<div class="col-lg-4 col-md-6 d-flex">                           
                            <div class="agent-card agency card flex-fill">
                                <div class="agent-img">
                                    <a [routerLink]="routes.agencyDetails">
                                        <img class="img-fluid" alt="Property Image" src="assets/img/property/property-03.png">
                                    </a>
                                    <div class="list-feature">
                                        <span>50 Listings</span>
                                    </div>
                                </div>
                                <div class="agent-content">
                                    <div class="rating">
										<span class="rating-count">
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star"></i>
											<i class="fa-solid fa-star"></i>
										</span>
                                        <p class="rating-review"><span>3.0</span>(10 Reviews)</p>
                                    </div>
									<div class="agency-user">
										<div class="agency-user-info">
											<h6>
												<a [routerLink]="routes.agencyDetails">Homes</a> 
											</h6>
											<p><i class="bx bx-map"></i>Las Vegas</p>
										</div>
									</div>
                                </div>	
                            </div>
						</div>
                        <!-- /Agent -->

                        <!-- Agent -->
						<div class="col-lg-4 col-md-6 d-flex">                           
                            <div class="agent-card agency card flex-fill">
                                <div class="agent-img">
                                    <a [routerLink]="routes.agencyDetails">
                                        <img class="img-fluid" alt="Property Image" src="assets/img/property/property-05.png">
                                    </a>
                                    <div class="list-feature">
                                        <span>55 Listings</span>
                                    </div>
                                </div>
                                <div class="agent-content">
                                    <div class="rating">
										<span class="rating-count">
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
										</span>
                                        <p class="rating-review"><span>5.0</span>(15 Reviews)</p>
                                    </div>
									<div class="agency-user">
										<div class="agency-user-info">
											<h6>
												<a [routerLink]="routes.agencyDetails">Queen Estate</a> 
											</h6>
											<p><i class="bx bx-map"></i>Pawnee City, NE</p>
										</div>
									</div>
                                </div>	
                            </div>
						</div>
                        <!-- /Agent -->

                        <!-- Agent -->
						<div class="col-lg-4 col-md-6 d-flex">                           
                            <div class="agent-card agency card flex-fill">
                                <div class="agent-img">
                                    <a [routerLink]="routes.agencyDetails">
                                        <img class="img-fluid" alt="Property Image" src="assets/img/property/property-04.png">
                                    </a>
                                    <div class="list-feature">
                                        <span>44 Listings</span>
                                    </div>
                                </div>
                                <div class="agent-content">
                                    <div class="rating">
										<span class="rating-count">
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
										</span>
                                        <p class="rating-review"><span>5.0</span>(23 Reviews)</p>
                                    </div>
									<div class="agency-user">
										<div class="agency-user-info">
											<h6>
												<a [routerLink]="routes.agencyDetails">Rent a Home</a> 
											</h6>
											<p><i class="bx bx-map"></i>Barron, WI</p>
										</div>
									</div>
                                </div>	
                            </div>
						</div>
                        <!-- /Agent -->
                        
                        <!-- Agent -->
						<div class="col-lg-4 col-md-6 d-flex">                           
                            <div class="agent-card agency card flex-fill">
                                <div class="agent-img">
                                    <a [routerLink]="routes.agencyDetails">
                                        <img class="img-fluid" alt="Property Image" src="assets/img/property/property-06.png">
                                    </a>
                                    <div class="list-feature">
                                        <span>60 Listings</span>
                                    </div>
                                </div>
                                <div class="agent-content">
                                    <div class="rating">
										<span class="rating-count">
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
											<i class="fa-solid fa-star checked"></i>
										</span>
                                        <p class="rating-review"><span>5.0</span>(25 Reviews)</p>
                                    </div>
									<div class="agency-user">
										<div class="agency-user-info">
											<h6>
												<a [routerLink]="routes.agencyDetails">Louis Realtors</a> 
											</h6>
											<p><i class="bx bx-map"></i>Correll, MN</p>
										</div>
									</div>
                                </div>	
                            </div>
						</div>
                        <!-- /Agent -->
					</div>
				</div>
			</div>
			<!-- /Content -->
