// angular/src/app/feature-module/pages/coming-soon/coming-soon.component.ts
import { Component, OnDestroy, Renderer2 } from '@angular/core';
import { CommonService } from '../../../shared/common/common.service';
import { routes } from '../../../shared/routes/routes';

@Component({
  selector: 'app-coming-soon',
  templateUrl: './coming-soon.component.html',
  styleUrl: './coming-soon.component.scss'
})
export class ComingSoonComponent implements OnDestroy {
  base = '';
  page = '';
  last = '';
  public routes = routes;
  constructor(
    private common: CommonService,
    private renderer: Renderer2
  ) {
    this.common.base.subscribe((res: string) => {
      this.base = res;
    });
    this.common.page.subscribe((res: string) => {
      this.page = res;
    });
    this.common.last.subscribe((res: string) => {
      this.last = res;
    });
    if(this.page == 'coming-soon') {
      this.renderer.addClass(document.body, 'error-page');
      this.renderer.addClass(document.body, 'login-body');
      this.renderer.addClass(document.body, 'p-0');
    }
  }
  ngOnDestroy(): void {
    this.renderer.removeClass(document.body, 'error-page');
    this.renderer.removeClass(document.body, 'login-body');
    this.renderer.removeClass(document.body, 'p-0');
  }
}

<div class="container">
    <!-- Header -->
    <header class="log-header">
        <a [routerLink] = "routes.home"><img class="img-fluid logo-dark" src="assets/img/logo.svg" alt="Logo"></a>
    </header>
    <!-- /Header -->
    
    <div class="error-box come-box">
        <h1>Coming Soon</h1>
        <p>We'll be here soon with our new awesome site, subscribe to be notified.</p>
        <h6>We'll Be Back Shortly</h6>
        <div class="footer-social-links">
            <ul class="nav">						
                <li>
                    <a href="javascript:void(0);"><i class="fa-brands fa-instagram hi-icon"></i></a>
                </li>						
                <li>
                    <a href="javascript:void(0);"><i class="fa-brands fa-twitter hi-icon"></i> </a>
                </li>						
                <li>
                    <a href="javascript:void(0);"><i class="fab fa-youtube hi-icon"></i></a>
                </li>
                <li>
                    <a href="javascript:void(0);"><i class="fa-brands fa-facebook-f hi-icon"></i></a>
                </li>
                <li>
                    <a href="javascript:void(0);"><i class="fa-brands fa-linkedin hi-icon"></i></a>
                </li>
            </ul>
        </div>
        <div class="serve-form">
            <form action="#">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Enter Email">
                    <button type="submit" class="btn button-notific btn-primary d-flex align-items-center">
                        <span>Notify Me</span>
                    </button>
                </div>
            </form>
        </div>
        <div class="back-button">
            <a [routerLink] = "routes.home" class="btn-maintance btn">Back to Home</a>
        </div>
    </div>

</div>

// react/src/feature-module/pages/comingSoon/index.tsx
import React from 'react'
import ImageWithBasePath from '../../../core/img'
import { Link } from "react-router-dom";
import { all_routes } from '../../router/all_routes';

const ComingSoon = () => {
  const routes = all_routes
  return (
    <div className="login-body">
    <div className="container">
        {/* Header */}
        <header className="log-header">
          <Link to={routes.home}><ImageWithBasePath className="img-fluid logo-dark" src="assets/img/logo.svg" alt="Logo" /></Link>
        </header>
        {/* /Header */}
        <div className="error-box come-box">
          <h1>Coming Soon</h1>
          <p>We'll be here soon with our new awesome site, subscribe to be notified.</p>
          <h6>We'll Be Back Shortly</h6>
          <div className="footer-social-links">
            <ul className="nav">						
              <li>
                <Link to="#"><i className="fa-brands fa-instagram hi-icon" /></Link>
              </li>						
              <li>
                <Link to="#"><i className="fa-brands fa-twitter hi-icon" /> </Link>
              </li>						
              <li>
                <Link to="#"><i className="fab fa-youtube hi-icon" /></Link>
              </li>
              <li>
                <Link to="#"><i className="fa-brands fa-facebook-f hi-icon" /></Link>
              </li>
              <li>
                <Link to="#"><i className="fa-brands fa-linkedin hi-icon" /></Link>
              </li>
            </ul>
          </div>
          <div className="serve-form">
            <form action="#">
              <div className="form-group">
                <input type="text" className="form-control" placeholder="Enter Email" />
                <button type="submit" className="btn button-notific btn-primary d-flex align-items-center">
                  <span>Notify Me</span>
                </button>
              </div>
            </form>
          </div>
          <div className="back-button">
            <Link to={routes.home} className="btn-maintance btn">Back to Home</Link>
          </div>
        </div>
      </div>
      </div>
  )
}

export default ComingSoon
